### ISSUE TITLE
Travis CI notifications import not working.

### ISSUE THREAD

**Issue by tobias-richter** [ansible/galaxy#1033]
##### SUMMARY
Hi,

i just followed this documentation to automate our role imports with travis:
https://galaxy.ansible.com/docs/contributing/importing.html#travis-ci

This currently applies to all of the roles of the wcm_io_devops namespace,

Example:
I added Travis CI for this role:
Galaxy: https://galaxy.ansible.com/wcm_io_devops/aem_service
Github: https://github.com/wcm-io-devops/ansible-aem-service/commit/245fef665b5e61038f46f64550a8483b0cfbf22b
Travis Build: https://travis-ci.org/wcm-io-devops/ansible-aem-service/builds/413089783

I assume that the API should list the notification, but i can not find any notification for this:
https://galaxy.ansible.com/api/v1/notifications/

When i try the formular at the bottom to post to the API i get a 500 server error.

Additonally also tried it as described the following approaches without success.

1. Travis Token in GUI

https://www.ansible.com/ansible-galaxy-automating-role-imports

This video seems not to be up to date since the option for the travis token is not available in the GUI anymore, or I was not able to find it.

2. Travis token via CLI

https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#travis-integrations

This also is not working, and with comment: https://github.com/ansible/galaxy/issues/55#issuecomment-336320468 this should not be needed anymore.

Maybe this is related to https://github.com/ansible/galaxy/issues/1012 because our namespace was renamed form "wcm-io-devops" to "wcm_io_devops"?

##### STEPS TO REPRODUCE
Restart a build of https://travis-ci.org/wcm-io-devops/ansible-aem-service

##### EXPECTED RESULTS
The role https://galaxy.ansible.com/wcm_io_devops/aem_service should be imported after travis build passes.

##### ACTUAL RESULTS
The role https://galaxy.ansible.com/wcm_io_devops/aem_service is not imported

**Comment by chouseknecht** [comment]
@tobias-richter 

Thanks for reporting this issue. Appreciate the help!

@newswangerd located the issue. Here's the traceback:

```
2018-08-07 10:57:56,846 DEBUG permissions: has_permission returned True
2018-08-07 10:57:56,923 ERROR exception: Internal Server Error: /api/v1/notifications/
Traceback (most recent call last):
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/galaxy/api/views/notification.py", line 142, in post
    owner = self._get_owner(github_user)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/galaxy/api/views/notification.py", line 240, in _get_owner
    username=settings.GITHUB_TASK_USERS[0])
IndexError: list index out of range
10.128.0.1 - - [07/Aug/2018:10:57:56 -0400] "POST /api/v1/notifications/ HTTP/1.1" 500 27 "-" "Travis CI Notifications"
```

Looks like we need to restore `GITHUB_TASK_USERS` in settings, and this will be fixed.

**Comment by tobias-richter** [comment]
@chouseknecht i am more than happy to help.
Please let me know when i can support e.g. by restarting the build.

**Comment by chouseknecht** [comment]
@tobias-richter 

Cool. You're now an owner of the `wcm_io_devops` namespace. You should be able to add repositories, and try out the Travis web hook.

**Comment by tobias-richter** [comment]
@chouseknecht looks good!

Galaxy: https://galaxy-qa.ansible.com/my-imports?namespace=wcm_io_devops&repository_name=aem_service&selected=215493&page_size=10

Github: https://github.com/wcm-io-devops/ansible-aem-service/commit/50ef465d840474e5db656f3e12866d4b1579913a

Travis: https://travis-ci.org/wcm-io-devops/ansible-aem-service/builds/413697468

The role was directly imported after the travis build finished.

**Comment by chouseknecht** [comment]
@tobias-richter 

Awesome! We'll get this pushed in this evening. Thank you for your help!

**Comment by tobias-richter** [comment]
Awesome! Thank you very much!

**Comment by chouseknecht** [comment]
@tobias-richter 

The fix was deployed to production. Closing.

**Comment by tobias-richter** [comment]
@chouseknecht i can confirm that this is now working on PROD.
