### ISSUE TITLE
Ansible-galaxy not working on Mac OS 10.12.6

### ISSUE THREAD

**Issue by TheFunkyTechnician** [ansible/galaxy#1189]
##### SUMMARY

Ansible-galaxy not working with any command. 

##### STEPS TO REPRODUCE

```sudo ansible-galaxy install Juniper.junos```

##### EXPECTED RESULTS

```- downloading role 'junos', owned by Juniper
- downloading role from https://github.com/Juniper/ansible-junos-stdlib/archive/2.0.0.tar.gz
- extracting Juniper.junos to /etc/ansible/roles/Juniper.junos
- Juniper.junos (2.0.0) was installed successfully```

##### ACTUAL RESULTS
<!--- What actually happened? Include screenshots, if applicable. -->

<!--- Paste verbatim tracebacks here, if applicable. -->
```JMALDONADO02:bin jmaldonado$ sudo ansible-galaxy install Juniper.juno
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ansible-galaxy", line 146, in <module>
    display.error("Unexpected Exception, this is probably a bug: %s" % to_text(e), wrap_text=False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/utils/display.py", line 290, in error
    self.display(new_msg, color=C.COLOR_ERROR, stderr=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/utils/display.py", line 137, in display
    msg2 = to_bytes(msg2, encoding=self._output_encoding(stderr=stderr))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/module_utils/_text.py", line 133, in to_bytes
    return obj.encode(encoding, errors)
LookupError: unknown encoding: 
JMALDONADO02:bin jmaldonado$ 
```

**Comment by newswangerd** [comment]
@TheFunkyTechnician Can you tell us what version you're using? You can just paste the output from `ansible-galaxy --version`

**Comment by TheFunkyTechnician** [comment]
```ansible --version
ansible 2.6.2
  config file = /private/etc/ansible/ansible.cfg
  configured module search path = [u'/Users/jmaldonado/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/2.7/bin/ansible
  python version = 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]```

**Comment by TheFunkyTechnician** [comment]
Thanks for responding so far. Appreciate it.
