### ISSUE TITLE
The SECRET_KEY setting must not be empty.

### ISSUE THREAD

**Issue by ChrisRo89** [ansible/galaxy#1289]
I got the following error when I try to run the docker image for latest (2.4) even if I set a ENV with this name. 

# docker logs galaxy
[2018-11-06 04:54:03 +0000] [8] [INFO] Starting gunicorn 19.7.1
[2018-11-06 04:54:03 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8)
[2018-11-06 04:54:03 +0000] [8] [INFO] Using worker: sync
[2018-11-06 04:54:03 +0000] [13] [INFO] Booting worker with pid: 13
[2018-11-06 04:54:04 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
[root@www ~]# docker logs galaxy                                                    [2018-11-06 04:54:03 +0000] [8] [INFO] Starting gunicorn 19.7.1
[2018-11-06 04:54:03 +0000] [8] [INFO] Listening at: http://0.0.0.0:8000 (8)
[2018-11-06 04:54:03 +0000] [8] [INFO] Using worker: sync                           [2018-11-06 04:54:03 +0000] [13] [INFO] Booting worker with pid: 13
[2018-11-06 04:54:04 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):                                                    File "/var/lib/galaxy/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()                                                             File "/var/lib/galaxy/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()                                                                  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()                                                       File "/var/lib/galaxy/venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()                                                       File "/var/lib/galaxy/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()                                                        File "/var/lib/galaxy/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)                                              File "/var/lib/galaxy/venv/lib/python2.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)                                                                File "/var/lib/galaxy/venv/lib/python2.7/site-packages/galaxy/wsgi.py", line 31, in <module>
    prepare_env()                                                                     File "/var/lib/galaxy/venv/lib/python2.7/site-packages/galaxy/__init__.py", line 49, in prepare_env
    if not settings.DEBUG:
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup                                                                       self._wrapped = Settings(settings_module)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 129, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
ImproperlyConfigured: The SECRET_KEY setting must not be empty.
[2018-11-06 04:54:04 +0000] [13] [INFO] Worker exiting (pid: 13)
[2018-11-06 04:54:04 +0000] [8] [INFO] Shutting down: Master
[2018-11-06 04:54:04 +0000] [8] [INFO] Reason: Worker failed to boot.

**Comment by cutwater** [comment]
You should set ENV variable `GALAXY_SECRET_KEY`.

**Comment by ChrisRo89** [comment]
Thank you Am 06.11.2018 12:11 schrieb Alexander Saprykin <notifications@github.com>:You should set ENV variable GALAXY_SECRET_KEY.
