### ISSUE TITLE
text encoding fail import collection with air_quote plugin with ["✌️", "✌️"] in code

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy#1454]
##### SUMMARY

Seeing a traceback in galaxydev importing a plugin with non-ascii in it (I'm fairly sure I had imported that before without problems).

While importing https://github.com/alikins/collection_reqs_test it fails to import air_quote.py (https://github.com/alikins/collection_reqs_test/blob/master/plugins/filter/air_quote.py) 
presumably on the line: https://github.com/alikins/collection_reqs_test/blob/15e7d0eb3e60af5704d9117c7ce7cf3d16b5376f/plugins/filter/air_quote.py#L17  

That line includes:

``` python
aq = ["✌️", text, "✌️"]
```

Viewing the galaxy import messages at https://galaxy-dev.ansible.com/my-imports?namespace=alikins&repository_name=collection_reqs_test&selected=280821&page_size=10 , the failure is:

```
Task "280821" failed: 'ascii' codec can't decode byte 0xe2 in position 392: ordinal not in range(128)
```

The galaxy-worker logs:

```
{"@timestamp": "2019-01-10T22:09:31.251102+00:00", "@version": 1, "exc_text": "Traceback (most recent call last):\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/worker/tasks.py\", line 115, in import_repository\n    _import_repository(import_task, logger)\n  File \"/usr/lib64/python3.6/contextlib.py\", line 52, in inner\n    return func(*args, **kwds)\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/worker/tasks.py\", line 155, in _import_repository\n    logger=logger)\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/repository.py\", line 40, in import_repository\n    return load_repository(clone_dir, logger)\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/repository.py\", line 50, in load_repository\n    return RepositoryLoader(directory, logger=logger).load()\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/repository.py\", line 78, in load\n    result = list(self._load_contents(contents))\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/repository.py\", line 115, in _load_contents\n    content = loader.load()\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/loaders/plugin.py\", line 57, in load\n    self._parse_plugin()\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/loaders/plugin.py\", line 78, in _parse_plugin\n    code = fp.read()\n  File \"/usr/lib64/python3.6/encodings/ascii.py\", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 392: ordinal not in range(128)", "filename": "tasks.py", "funcName": "import_repository", "levelname": "ERROR", "levelno": 40, "lineno": 131, "log": "2019-01-10 17:09:31,251 none ERROR galaxy.worker.tasks: 'ascii' codec can't decode byte 0xe2 in position 392: ordinal not in range(128)\nTraceback (most recent call last):\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/worker/tasks.py\", line 115, in import_repository\n    _import_repository(import_task, logger)\n  File \"/usr/lib64/python3.6/contextlib.py\", line 52, in inner\n    return func(*args, **kwds)\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/worker/tasks.py\", line 155, in _import_repository\n    logger=logger)\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/repository.py\", line 40, in import_repository\n    return load_repository(clone_dir, logger)\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/repository.py\", line 50, in load_repository\n    return RepositoryLoader(directory, logger=logger).load()\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/repository.py\", line 78, in load\n    result = list(self._load_contents(contents))\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/repository.py\", line 115, in _load_contents\n    content = loader.load()\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/loaders/plugin.py\", line 57, in load\n    self._parse_plugin()\n  File \"/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/loaders/plugin.py\", line 78, in _parse_plugin\n    code = fp.read()\n  File \"/usr/lib64/python3.6/encodings/ascii.py\", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 392: ordinal not in range(128)", "message": "'ascii' codec can't decode byte 0xe2 in position 392: ordinal not in range(128)", "message_format": "'ascii' codec can't decode byte 0xe2 in position 392: ordinal not in range(128)", "module": "tasks", "name": "galaxy.worker.tasks", "pathname": "/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/worker/tasks.py", "process": 17, "processName": "Worker-1", "relativeCreated": 61377097.25165367, "request_id": "none", "thread": 139627707283264, "threadName": "MainThread"}
[2019-01-10 17:09:31,267: ERROR/MainProcess] Task galaxy.worker.tasks.import_repository[c02f3cf9-da2d-4cd3-8c40-2d95784fed43] raised unexpected: UnicodeDecodeError('ascii', b'# Copyright (c) 2017 Ansible Project\n# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)\n#  -*- coding: utf-8 -*-\n\nfrom __future__ import (absolute_import, division, print_function)\n__metaclass__ = type\n\n\nANSIBLE_METADATA = {\n    \'metadata_version\': \'1.1\',\n    \'status\': [\'preview\'],\n    \'supported_by\': \'community\'\n}\n\n\ndef air_quote(text):\n    aq = ["\xe2\x9c\x8c\xef\xb8\x8f", text, "\xe2\x9c\x8c\xef\xb8\x8f"]\n    return \'\'.join(aq)\n\n\n# ---- Ansible filters ----\nclass FilterModule(object):\n    \'\'\' Air quote filter \'\'\'\n\n    def filters(self):\n        return {\n            \'air_quote\': air_quote\n        }\n', 392, 393, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/worker/tasks.py", line 115, in import_repository
    _import_repository(import_task, logger)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/worker/tasks.py", line 155, in _import_repository
    logger=logger)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/repository.py", line 40, in import_repository
    return load_repository(clone_dir, logger)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/repository.py", line 50, in load_repository
    return RepositoryLoader(directory, logger=logger).load()
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/repository.py", line 78, in load
    result = list(self._load_contents(contents))
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/repository.py", line 115, in _load_contents
    content = loader.load()
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/loaders/plugin.py", line 57, in load
    self._parse_plugin()
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/galaxy/importer/loaders/plugin.py", line 78, in _parse_plugin
    code = fp.read()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 392: ordinal not in range(128)
```

##### STEPS TO REPRODUCE

Try to import https://github.com/alikins/collection_reqs_test  or a fork of it into galaxydev

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
@alikins re-tested and confirmed fixed
