### ISSUE TITLE
Import fails with DB integrity error when repository has empty description

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy#1464]
##### SUMMARY
When importing a repository for which the description on Github is empty, the import process fails with an unhelpful internal database integrity exception.

##### STEPS TO REPRODUCE
Create a repository with valid roles but no description on Github. Create the repo and push up the role and add no other details, like here: https://github.com/orionuser1/without-description

##### ACTUAL RESULTS

When running the import that fails:
```
$ ansible-galaxy import --server=http://172.29.22.242:8000 orionuser1 even-more-content
Successfully submitted import request 14
Starting import: task_id=14, repository=orionuser1/even-more-content

===== LINTING ROLE: test-role-a =====
yamllint OK.
ansible-lint Warnings:
./roles/test-role-a/meta/main.yml:1: [E701] Role info should contain min_ansible_version

===== IMPORTING ROLE: test_role_a =====
Adding role metadata tags
Adding role platforms
Invalid platform: "Ubuntu-xenial", skipping.

Task "14" failed: null value in column "description" violates not-null constraint
DETAIL:  Failing row contains (4, 2019-01-22 20:13:32.662757+00, 2019-01-22 21:16:18.644337+00, even-more-content, t, 78434670485ffba17fe17f0f4af1e829df326497, add test-role-
```

From logs:
```
21:16:18 celery.1    | [2019-01-22 16:16:18,738: ERROR/MainProcess] Task galaxy.worker.tasks.import_repository[4ad03a50-8f99-4d4e-9f8a-183117c18841] raised unexpected: IntegrityError('null value in column "description" violates not-null constraint\nDETAIL:  Failing row contains (4, 2019-01-22 20:13:32.662757+00, 2019-01-22 21:16:18.688034+00, even-more-content, t, 78434670485ffba17fe17f0f4af1e829df326497, add test-role-a, https://api.github.com/repos/orionuser1/even-more-content/git/co..., 2019-01-22 19:57:37+00, 0, 0, 0, 0, even_more_content, master, 1, null, , , https://github.com/orionuser1/even-more-content/issues, multi, 8, 0, f, null, 4.625, 2019-01-22 20:13:49.45879+00, f, 0).\n',)
21:16:18 celery.1    | Traceback (most recent call last):
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
21:16:18 celery.1    |     R = retval = fun(*args, **kwargs)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
21:16:18 celery.1    |     return self.run(*args, **kwargs)
21:16:18 celery.1    |   File "/galaxy/galaxy/worker/tasks.py", line 133, in import_repository
21:16:18 celery.1    |     reason='Task "{}" failed: {}'.format(import_task.id, str(e)))
21:16:18 celery.1    |   File "/galaxy/galaxy/main/models.py", line 854, in finish_failed
21:16:18 celery.1    |     self.save()
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 808, in save
21:16:18 celery.1    |     force_update=force_update, update_fields=update_fields)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 848, in save_base
21:16:18 celery.1    |     update_fields=update_fields, raw=raw, using=using,
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in send
21:16:18 celery.1    |     for receiver in self._live_receivers(sender)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
21:16:18 celery.1    |     for receiver in self._live_receivers(sender)
21:16:18 celery.1    |   File "/galaxy/galaxy/main/signals/handlers.py", line 89, in import_task_post_save
21:16:18 celery.1    |     repo.save()
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 808, in save
21:16:18 celery.1    |     force_update=force_update, update_fields=update_fields)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
21:16:18 celery.1    |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 905, in _save_table
21:16:18 celery.1    |     forced_update)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 955, in _do_update
21:16:18 celery.1    |     return filtered._update(values) > 0
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 667, in _update
21:16:18 celery.1    |     return query.get_compiler(self.db).execute_sql(CURSOR)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1204, in execute_sql
21:16:18 celery.1    |     cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
21:16:18 celery.1    |     raise original_exception
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
21:16:18 celery.1    |     cursor.execute(sql, params)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
21:16:18 celery.1    |     return super(CursorDebugWrapper, self).execute(sql, params)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
21:16:18 celery.1    |     return self.cursor.execute(sql, params)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
21:16:18 celery.1    |     six.reraise(dj_exc_type, dj_exc_value, traceback)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/utils/six.py", line 685, in reraise
21:16:18 celery.1    |     raise value.with_traceback(tb)
21:16:18 celery.1    |   File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
21:16:18 celery.1    |     return self.cursor.execute(sql, params)
21:16:18 celery.1    | django.db.utils.IntegrityError: null value in column "description" violates not-null constraint
21:16:18 celery.1    | DETAIL:  Failing row contains (4, 2019-01-22 20:13:32.662757+00, 2019-01-22 21:16:18.688034+00, even-more-content, t, 78434670485ffba17fe17f0f4af1e829df326497, add test-role-a, https://api.github.com/repos/orionuser1/even-more-content/git/co..., 2019-01-22 19:57:37+00, 0, 0, 0, 0, even_more_content, master, 1, null, , , https://github.com/orionuser1/even-more-content/issues, multi, 8, 0, f, null, 4.625, 2019-01-22 20:13:49.45879+00, f, 0).
21:16:18 celery.1    |
```

**Comment by alikins** [comment]
https://github.com/ansible/galaxy/issues/902 is a similar failure for this scenario (ie, no description set on a github repo). Not the same failure, but the same trigger.
