### ISSUE TITLE
Multi Content repos fail to import when description is not set

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy#1497]
##### SUMMARY

If the Git Hub description isn't set on a multi content repo it causes the import process to fail.

##### STEPS TO REPRODUCE

- Clone: https://github.com/atestuseraccount/debops-examples
- Remove the Git Hub description here:
![screen shot 2019-01-30 at 10 27 05 am](https://user-images.githubusercontent.com/6063371/51991756-c66a2a80-2479-11e9-8261-820c87c2f715.png)
- Import the repo into galaxy.

##### EXPECTED RESULTS

- Import should succeed

##### ACTUAL RESULTS

- Import fails with the following error:

```
[2019-01-30 09:41:50,306: ERROR/MainProcess] Task galaxy.worker.tasks.import_repository[977c07bc-0618-42cc-afd1-ee5cec44b6e0] raised unexpected: IntegrityError('null value in column "description" violates not-null constraint\nDETAIL:  Failing row contains (82227, 2019-01-30 14:32:50.838017+00, 2019-01-30 14:41:50.262127+00, debops-import-test, t, 0ba6d81a342f6c0c838e181d8f9df1c8a1799b26, --, https://api.github.com/repos/newswangerd/debops-import-test/git/..., 2019-01-30 $
4:40:20+00, 0, 0, 0, 1, debops_import_test, master, 2877, null, , , , multi, 25492, 0, f, null, null, null, t, 0).\n',)
Traceback (most recent call last):
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/galaxy/galaxy/worker/tasks.py", line 133, in import_repository
    reason='Task "{}" failed: {}'.format(import_task.id, str(e)))
  File "/galaxy/galaxy/main/models.py", line 855, in finish_failed
    self.save()
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 758, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/galaxy/galaxy/main/signals/handlers.py", line 89, in import_task_post_save
    repo.save()
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 812, in _save_table
    forced_update)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 861, in _do_update
    return filtered._update(values) > 0
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 712, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1383, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/galaxy/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "description" violates not-null constraint
DETAIL:  Failing row contains (82227, 2019-01-30 14:32:50.838017+00, 2019-01-30 14:41:50.262127+00, debops-import-test, t, 0ba6d81a342f6c0c838e181d8f9df1c8a1799b26, --, https://api.github.com/repos/newswangerd/debops-import-test/git/...,
2019-01-30 14:40:20+00, 0, 0, 0, 1, debops_import_test, master, 2877, null, , , , multi, 25492, 0, f, null, null, null, t, 0).
```

**Comment by alikins** [comment]
See also:
https://github.com/ansible/galaxy/issues/1464
https://github.com/ansible/galaxy/issues/902#issuecomment-439137852  (to a lesser degree)

**Comment by awcrosby** [comment]
Closing, multi-content repos no longer importable with #1682
