### ISSUE TITLE
Missing migration on galaxy-dev for new importtask collection field

### ISSUE THREAD

**Issue by ironfroggy** [ansible/galaxy#1649]
##### SUMMARY
It appears that migration `0131_import_task_collection_support` wasn't run for the galaxy-dev deploy, based on the traceback below showing the `collection_id` field missing.

##### STEPS TO REPRODUCE
Hit any API point that tries to query the `importtask` table.

##### EXPECTED RESULTS
I did not expect a 500 error and a traceback in logs.

##### ACTUAL RESULTS
I got a 500 error and a traceback in logs.

```
Traceback (most recent call last):
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/galaxy/api/views/views.py", line 439, in post
    import_branch=github_reference, user_initiated=True)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/galaxy/api/tasks.py", line 35, in create_import_task
    state=models.ImportTask.STATE_PENDING
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "collection_id" of relation "main_importtask" does not exist
LINE 1: ... ("created", "modified", "description", "active", "collectio...
```

**Comment by ironfroggy** [comment]
Tests are working again after this change and deploy: https://github.com/ansible/galaxy-deploy/commit/d2dbecd40a4bb96af20ed8be856dd7c94611bc10
