### ISSUE TITLE
mazer publish to galaxy-dev gets a 302 response. Expected? (possible mazer bug?)

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy#1720]
##### SUMMARY

A `mazer publish` to https://galaxy-dev.ansible.com gets a 302 "Found" response from cloudflare "redirecting" to same URL.

Mazer currently expects 202 "Accepted" response for that POST and currently considers anything else an error. 

If the 302 is expected, then this is a mazer client error.  It looks like a 302 is the expected response for a request for cloudflare.

If the 302 is not expected, there may be problems elsewhere.

Should 

(Either way, mazer should probably be updated to handle the 302 Found for that url. Currently, it is a little odd because mazers http request handling for that request is different than other requests that may be okay with 302's)

See also
https://gist.github.com/alikins/a5a2adb1b475b50afff6c681121b3c63

##### STEPS TO REPRODUCE

Prereqs: 
- need recent devel branch mazer (or at least 0.4.0 or newer)
- need a collection artifact to upload
  - for, fork and clone https://github.com/alikins/collection_reqs_test
  - change it's namespace in galaxy.yml
  - `mazer build` to create an artifact in releases/
- need galaxy-dev api token (from https://galaxy-dev.ansible.com/me/preferences 'API Key')

```
# cd to where the collection artifact is (releases/ )
# Assuming the galaxy api token above is in env var GALAXY_DEV_TOKEN
# mazer publish

$ mazer --server https://galaxy-dev.ansible.com publish --api-key "${GALAXY_DEV_TOKEN}" alikins-collection_inspect-0.0.20.tar.gz
```

##### EXPECTED RESULTS

Expect a message about the import being accepted and a return with the imports view url

##### ACTUAL RESULTS

```
(mazer040test) [newswoop:F29:releases (master % u=)]$ mazer --server https://galaxy-dev.ansible.com publish --api-key "${GALAXY_DEV_TOKEN}" alikins-collection_inspect-0.0.20.tar.gz
Error publishing alikins-collection_inspect-0.0.20.tar.gz - Error transferring file "alikins-collection_inspect-0.0.20.tar.gz" to Galaxy server (https://galaxy-dev.ansible.com): 302 - Found
```

The POST request to https://galaxy-dev.ansible.com/api/v2/collections/ returns a 302 with a redirect Location header that points to the same url https://galaxy-dev.ansible.com/api/v2/collections/.

**But note the 302 appears to be coming from cloudflare CDN.**

With mazer logs set to DEBUG, ~/.ansible/mazer.log

```
[2019-04-09 10:30:42,800 23281 D] ansible_galaxy.rest_api __init__:95  - Using galaxy server URL https://galaxy-dev.ansible.com with ignore_certs=False
[2019-04-09 10:30:42,800 23281 D] ansible_galaxy.rest_api __init__:109 - User Agent: Mazer/0.4.0 (linux; python:3.6.8) ansible_galaxy/0.4.0
[2019-04-09 10:30:42,801 23281 D] ansible_galaxy.actions.publish _publish:62  - Publishing file alikins-collection_inspect-0.0.20.tar.gz with data: {"sha256": "f583261c85ee4dcf0fe3e442f7414bbb6b9e364052e730ddc5fcd4626965893e", "name": "collection_inspect", "version": "0.0.20"}
[2019-04-09 10:30:42,801 23281 D] ansible_galaxy.rest_api wrapped:68  - Initial connection to galaxy_server: https://galaxy-dev.ansible.com
[2019-04-09 10:30:43,192 23281 D] ansible_galaxy.rest_api.GalaxyAPI _get_server_api_version:211 - Server API version of URL https://galaxy-dev.ansible.com/api/ is "v1"
[2019-04-09 10:30:43,193 23281 D] ansible_galaxy.rest_api publish_file:284 - url: https://galaxy-dev.ansible.com/api/v2/collections/
[2019-04-09 10:30:43,261 23281 D] ansible_galaxy.rest_api publish_file:311 - code: 302
[2019-04-09 10:30:43,262 23281 D] ansible_galaxy.rest_api publish_file:312 - info: Date: Tue, 09 Apr 2019 14:30:43 GMT
Content-Length: 0
Connection: keep-alive
Set-Cookie: __cfduid=ddd0e3c77aa2ffd8b15c5c402207286d61554820243; expires=Wed, 08-Apr-20 14:30:43 GMT; path=/; domain=.ansible.com; HttpOnly
Cache-Control: no-cache
Location: https://galaxy-dev.ansible.com/api/v2/collections/
Server: cloudflare
CF-RAY: 4c4d2e384cd59f35-IAD


[2019-04-09 10:30:43,267 23281 D] ansible_galaxy.rest_api publish_file:313 - reason: Found
[2019-04-09 10:30:43,268 23281 D] ansible_galaxy.rest_api publish_file:316 - response_body: b''
[2019-04-09 10:30:43,268 23281 E] ansible_galaxy_cli.main main:46  - Error publishing alikins-collection_inspect-0.0.20.tar.gz - Error transferring file "alikins-collection_inspect-0.0.20.tar.gz" to Galaxy server (https://galaxy-dev.ansible.com): 302 - Found
Traceback (most recent call last):
  File "/home/adrian/src/mazer/ansible_galaxy_cli/main.py", line 35, in main
    exit_code = cli.run()
  File "/home/adrian/src/mazer/ansible_galaxy_cli/cli/galaxy.py", line 218, in run
    return self.execute()
  File "/home/adrian/src/mazer/ansible_galaxy_cli/cli/__init__.py", line 152, in execute
    return fn()
  File "/home/adrian/src/mazer/ansible_galaxy_cli/cli/galaxy.py", line 299, in execute_publish
    display_callback=self.display)
  File "/home/adrian/src/mazer/ansible_galaxy/actions/publish.py", line 80, in publish
    display_callback=display_callback)
  File "/home/adrian/src/mazer/ansible_galaxy/actions/publish.py", line 64, in _publish
    b_response_body = api.publish_file(data, archive_path, publish_api_key)
  File "/home/adrian/src/mazer/ansible_galaxy/rest_api.py", line 81, in wrapped
    return method(self, *args, **kwargs)
  File "/home/adrian/src/mazer/ansible_galaxy/rest_api.py", line 325, in publish_file
    archive_path=archive_path
ansible_galaxy.exceptions.GalaxyPublishError: Error publishing alikins-collection_inspect-0.0.20.tar.gz - Error transferring file "alikins-collection_inspect-0.0.20.tar.gz" to Galaxy server (https://galaxy-dev.ansible.com): 302 - Found
```

**Comment by alikins** [comment]
mazer bug, see https://github.com/ansible/mazer/issues/217 and https://github.com/ansible/mazer/issues/218
