### ISSUE TITLE
Unable to import role

### ISSUE THREAD

**Issue by wildone** [ansible/galaxy#1730]
##### SUMMARY
Unable to import role from galaxy using following command ```ansible-galaxy install -vvv aem_design.aem_security_test -p ./roles```

Accessing ```https://galaxy.ansible.com/api/v1/roles/?owner__username=aem_design&name=aem_security_test``` produces  ```Server Error (500)``` error :(

##### STEPS TO REPRODUCE
Run following:
```ansible-galaxy install -vvv aem_design.aem_security_test -p ./roles```

##### EXPECTED RESULTS
Expect the role to be downloaded into local roles folder

##### ACTUAL RESULTS
```
ansible-galaxy install -vvv aem_design.aem_security_test -p ./roles
ansible-galaxy 2.7.10
  config file = /Users/max.barrass/projects/gitlab/aemdesign-parent/aemdesign-operations/aemdesign-deploy/ansible.cfg
  configured module search path = ['/usr/share/ansible', '/Users/max.barrass/projects/gitlab/aemdesign-parent/aemdesign-operations/aemdesign-deploy/library/ansible-modules']
  ansible python module location = /Users/max.barrass/.virtualenvs/aemdesign.3.7.2/lib/python3.7/site-packages/ansible
  executable location = /Users/max.barrass/.virtualenvs/aemdesign.3.7.2/bin/ansible-galaxy
  python version = 3.7.2 (default, Feb 12 2019, 08:15:36) [Clang 10.0.0 (clang-1000.11.45.5)]
Using /Users/max.barrass/projects/gitlab/aemdesign-parent/aemdesign-operations/aemdesign-deploy/ansible.cfg as config file
Opened /Users/max.barrass/.ansible_galaxy
Processing role aem_design.aem_security_test
Opened /Users/max.barrass/.ansible_galaxy
- downloading role 'aem_security_test', owned by aem_design
https://galaxy.ansible.com/api/v1/roles/?owner__username=aem_design&name=aem_security_test
ERROR! Unexpected Exception, this is probably a bug: Expecting value: line 1 column 1 (char 0)
the full traceback was:

Traceback (most recent call last):
  File "/Users/max.barrass/.virtualenvs/aemdesign.3.7.2/bin/ansible-galaxy", line 118, in <module>
    exit_code = cli.run()
  File "/Users/max.barrass/.virtualenvs/aemdesign.3.7.2/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 162, in run
    self.execute()
  File "/Users/max.barrass/.virtualenvs/aemdesign.3.7.2/lib/python3.7/site-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/Users/max.barrass/.virtualenvs/aemdesign.3.7.2/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 398, in execute_install
    installed = role.install()
  File "/Users/max.barrass/.virtualenvs/aemdesign.3.7.2/lib/python3.7/site-packages/ansible/galaxy/role.py", line 210, in install
    role_data = api.lookup_role_by_name(self.src)
  File "/Users/max.barrass/.virtualenvs/aemdesign.3.7.2/lib/python3.7/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/Users/max.barrass/.virtualenvs/aemdesign.3.7.2/lib/python3.7/site-packages/ansible/galaxy/api.py", line 193, in lookup_role_by_name
    data = self.__call_galaxy(url)
  File "/Users/max.barrass/.virtualenvs/aemdesign.3.7.2/lib/python3.7/site-packages/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/Users/max.barrass/.virtualenvs/aemdesign.3.7.2/lib/python3.7/site-packages/ansible/galaxy/api.py", line 96, in __call_galaxy
    res = json.loads(to_text(e.fp.read(), errors='surrogate_or_strict'))
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by wildone** [comment]
Can now import had to switch namespaces :D
