### ISSUE TITLE
NoneType object has no attribute 'get'

### ISSUE THREAD

**Issue by TemperingPick** [ansible/galaxy#175]
Command I am using:
ansible-galaxy install -r roles/requirements.yml

Sample requirements.yml:
`---

- src: http://myprivterepo.git
  name: disable_something
  scm: git

- src: http://myprivterepo.git
  name: install_awx
  scm: git

- src: http://myprivterepo.git
  name: install_something
  scm: git

- src: http://myprivterepo.git
  name: install_something
  scm: git

- src: http://myprivterepo.git
  name: setup__something
  scm: git
`

Full output:
`ERROR! Unexpected Exception: 'NoneType' object has no attribute 'get'
the full traceback was:

Traceback (most recent call last):
  File "/opt/app/python/bin/ansible-galaxy", line 109, in <module>
    exit_code = cli.run()
  File "/opt/app/python/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 138, in run
    self.execute()
  File "/opt/app/python/lib/python2.7/site-packages/ansible/cli/__init__.py", line 149, in execute
    fn()
  File "/opt/app/python/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 394, in execute_install
    role_dependencies = role.metadata.get('dependencies') or []
AttributeError: 'NoneType' object has no attribute 'get'
`
The role installs just fine, but it stops after installing one role.

**Comment by phpengine** [comment]
I'm having this too - anyone?

**Comment by phpengine** [comment]
I figured it out. If the meta.main.yml  (of the last role installed) is empty, then it complains. To solve it, I added a standard meta/main.yml, pushed it to a new branch, then set that new branch in the requirements file. I then get no errors.
