### ISSUE TITLE
Import fails when importing renamed repository from GitHub keeping original name on Galaxy

### ISSUE THREAD

**Issue by hudecof** [ansible/galaxy#177]
Hi,

whern I try to enable my repository `hudecof/ansible_nginx-repo` I have got HTTP 500 error.

```
An error occurred while attempting to start the import. 
Error: Request to /api/v1/imports/ resulted in 500 - INTERNAL SERVER ERROR
```

  thanks

**Comment by cutwater** [comment]
Hi @hudecof,

Thanks for your report. Can you please provide additional information for us to investigate: 
* approximate time when issue occured,
* can you reproduce it each time when you update role,
* is any other of your roles affected.

Thanks

**Comment by hudecof** [comment]
Hi @cutwater ,

- first time I got this error was last week
- every attempt to enable/sychro the role ends with this error
- not other roles affected

I was refactoring the roles and the role names. The github repository is `https://github.com/hudecof/ansible_nginx-repo`, but the original name before rename was `https://github.com/hudecof/ansible_nginx_repo`.

The the galaxy the name is overwritten to `nginx-repo`

**Comment by cutwater** [comment]
According to server logs an exception on unique index check occures:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/galaxy/api/views.py", line 397, in post
    'is_valid':    False,
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 407, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 447, in _create_object_from_params
    six.reraise(*exc_info)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 439, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/lib/python2.7/site-packages/galaxy/main/models.py", line 71, in save
    super(BaseModel, self).save(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/lib64/python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/usr/lib64/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib64/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib64/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib64/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "main_role_namespace_36aa1070a7d8dc70_uniq"
DETAIL:  Key (namespace, name)=(ypid, persistent_paths) already exists.
```

**Steps to reproduce:**

1. Ensure GitHub repository is imported to Galaxy and has name `A`.
2. Rename repository on GitHub: `A -> B`
3. Refresh repository list on Galaxy.
4. Import repository to Galaxy.
5. Rename repository from `B` to `A` on Galaxy.

Actual behavior:

Import fails with error

```Error saving role: duplicate key value violates unique constraint "main_role_namespace_36aa1070a7d8dc70_uniq" DETAIL: Key (namespace, name)=(cutwater, galaxy-test) already exists.```

Expected behavior

Import succeeds.

**Comment by cutwater** [comment]
@hudecof try a workaround for now:

1. Rename repository to it's original name.
2. Refresh repository list on Galaxy
3. Enable (import) repository with to Galaxy. Make sure it's name is `nginx-repo`.
4. In case import finished successfully disable repository (by pressing switch control on the left of your repository name)
5. Rename repository to new name on GitHub.
6. Refresh and import it again on Galaxy.

**Comment by hudecof** [comment]
@cutwater thanks, workaroud works.
If you have any internal ticket about this issue you could close thiso one.

**Comment by sdarwin** [comment]
Hi @cutwater ,
During the above mentioned workaround it says "Are you sure you want to delete this role? Download count and other statistics will be lost." Perhaps another ticket should be opened to enable a way to retain download count and other statistics? In other words - "be able to rename a github repo". What do you think?

**Comment by sdarwin** [comment]
Solved. The problem I had was regarding a capitalization change. So, maybe this will help someone else in the future. In order to transition from ansible-nginx to Ansible-Nginx these are the steps:
- Rename github repo from ansible-nginx to ansible-role-nginx
- Refresh import list in Galaxy
- Rename github repo from ansible-role-nginx to Ansible-Nginx
- Refresh import list in Galaxy
