### ISSUE TITLE
Crash when using ansible-galaxy import

### ISSUE THREAD

**Issue by xlz-jgoutin** [ansible/galaxy#1947]
##### SUMMARY

Crash when calling ansible-galaxy import

##### STEPS TO REPRODUCE

`ansible-galaxy import accelize ansible-role-aws-fpga --role-name aws-fpga -vvv`

##### EXPECTED RESULTS

Success

##### ACTUAL RESULTS

Crash, see traceback.

```
ansible-galaxy 2.8.2
  config file = None
  configured module search path = ['/home/fedora/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fedora/.local/share/virtualenvs/fedora-sUyKfHtp/lib/python3.7/site-packages/ansible
  executable location = /home/fedora/.local/share/virtualenvs/fedora-sUyKfHtp/bin/ansible-galaxy
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
No config file found; using defaults
Opened /home/fedora/.ansible_galaxy
https://galaxy.ansible.com/api/v1/imports/
ERROR! Unexpected Exception, this is probably a bug: Expecting value: line 1 column 1 (char 0)
the full traceback was:

Traceback (most recent call last):
  File "/home/fedora/.local/share/virtualenvs/fedora-sUyKfHtp/bin/ansible-galaxy", line 110, in <module>
    exit_code = cli.run()
  File "/home/fedora/.local/share/virtualenvs/fedora-sUyKfHtp/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 149, in run
    self.execute()
  File "/home/fedora/.local/share/virtualenvs/fedora-sUyKfHtp/lib/python3.7/site-packages/ansible/cli/__init__.py", line 93, in execute
    fn()
  File "/home/fedora/.local/share/virtualenvs/fedora-sUyKfHtp/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 604, in execute_import
    role_name=context.CLIARGS['role_name'])
  File "/home/fedora/.local/share/virtualenvs/fedora-sUyKfHtp/lib/python3.7/site-packages/ansible/galaxy/api.py", line 54, in wrapped
    return method(self, *args, **kwargs)
  File "/home/fedora/.local/share/virtualenvs/fedora-sUyKfHtp/lib/python3.7/site-packages/ansible/galaxy/api.py", line 153, in create_import_task
    data = self.__call_galaxy(url, args=urlencode(args), method="POST")
  File "/home/fedora/.local/share/virtualenvs/fedora-sUyKfHtp/lib/python3.7/site-packages/ansible/galaxy/api.py", line 54, in wrapped
    return method(self, *args, **kwargs)
  File "/home/fedora/.local/share/virtualenvs/fedora-sUyKfHtp/lib/python3.7/site-packages/ansible/galaxy/api.py", line 94, in __call_galaxy
    res = json.loads(to_text(e.fp.read(), errors='surrogate_or_strict'))
  File "/usr/lib64/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by xlz-jgoutin** [comment]
After changing the Following `ansible.galaxy.api.py` code (Line 84):
```python
    @g_connect
    def __call_galaxy(self, url, args=None, headers=None, method=None):
        if args and not headers:
            headers = self.__auth_header()
        try:
            display.vvv(url)
            resp = open_url(url, data=args, validate_certs=self._validate_certs, headers=headers, method=method,
                            timeout=20)
            data = json.loads(to_text(resp.read(), errors='surrogate_or_strict'))
        except HTTPError as e:
            err_resp = to_text(e.fp.read(), errors='surrogate_or_strict')
            try:
                details = json.loads(err_resp)['detail']
            except json.decoder.JSONDecodeError:
                # Fall back if error is not JSON formated
                details = err_resp
            raise AnsibleError(details)
        return data
```
I get:
```
ansible-galaxy 2.8.2
  config file = None
  configured module search path = ['/home/fedora/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fedora/.local/share/virtualenvs/fedora-sUyKfHtp/lib/python3.7/site-packages/ansible
  executable location = /home/fedora/.local/share/virtualenvs/fedora-sUyKfHtp/bin/ansible-galaxy
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
No config file found; using defaults
Opened /home/fedora/.ansible_galaxy
https://galaxy.ansible.com/api/v1/imports/
ERROR! <h1>Server Error (500)</h1>
```
So, there is two issues:
* Error 500 on server.
* Ansible galaxy tries to parse this error as JSON, but error is not in JSON format. I suggest to add a fall back in case the JSON conversion fail to print the raw error (Like in my code example).

**Comment by chouseknecht** [comment]
@xlz-jgoutin 

Is this all the result of a bad import command. Your example is `ansible-galaxy import accelize ansible-role-aws-fpga --role-name aws-fpga -vvv`. There should be a `.` between `accelize` and `ansible-role-aws-fpga`

**Comment by chouseknecht** [comment]
@xlz-jgoutin 

I don't see an `accelize` namespace in Galaxy.

**Comment by chouseknecht** [comment]
@xlz-jgoutin 

It appears the correct namespace is `accelize_application`. Although, that's been disabled for some reason.

Created the namespace `accelize`. You should be able to import to it now. The correct command would be:

```
ansible-galaxy import accelize.ansible-role-aws-fpga --role-name aws-fpga -vvv
```

Don't know if `--role-name` works. If not, you can use the `role_name` parameter in `meta/main.yml`.

**Comment by chouseknecht** [comment]
@xlz-jgoutin 

Before running the import, visit the My Content page in Galaxy and edit the `accelize` namespace. Within the namespace properties, you'll need to associate the GitHub Org (i.e. the provider namespace).

**Comment by xlz-jgoutin** [comment]
Thank you, I successfully imported the role.

Some feedbacks:

> @xlz-jgoutin
> 
> Is this all the result of a bad import command. Your example is `ansible-galaxy import accelize ansible-role-aws-fpga --role-name aws-fpga -vvv`. There should be a `.` between `accelize` and `ansible-role-aws-fpga`

The help for ansible-galaxy import command seems to be wrong (`github_user github_repo` instead of `github_user.github_repo`) :

```
$ ansible-galaxy import --help
Usage: ansible-galaxy import [options] github_user github_repo
```

Same in the Ansible documentation: https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html?highlight=galaxy#import-a-role

The command error message, in this case, should be improved. I didn't understand what was wrong.
The server should return a more explicit error (400 Error  (Bad request) with a detailed message, instead of 500 that mean that "the error is server side, please try later").

I can eventually do a PR for the not JSON formatted error fallback (With the code below), but ideally, the server should always return JSON.

**Comment by chouseknecht** [comment]
@xlz-jgoutin 

The following works from the CLI. Notice that the GitHub user is actually `Accelize`. 

```
ansible-galaxy -vvv import Accelize ansible-role-accelize-drm
ansible-galaxy 2.7.10
  config file = /Users/chouseknecht/ansible.cfg
  configured module search path = [u'/Users/chouseknecht/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/chouseknecht/.pyenv/versions/2.7.14/envs/venv27/lib/python2.7/site-packages/ansible
  executable location = /Users/chouseknecht/.pyenv/versions/venv27/bin/ansible-galaxy
  python version = 2.7.14 (default, Nov 14 2017, 23:24:24) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]
Using /Users/chouseknecht/ansible.cfg as config file
Opened /Users/chouseknecht/.ansible_galaxy
https://galaxy.ansible.com/api/v1/imports/
Successfully submitted import request 453207
https://galaxy.ansible.com/api/v1/imports/?id=453207
Starting import: task_id=453207, repository=Accelize/ansible-role-accelize-drm

https://galaxy.ansible.com/api/v1/imports/?id=453207
===== LOADING ROLE =====
Checking role metadata tags
Checking role platforms
Checking role cloud platforms
Checking role dependencies

===== LINTING ROLE: accelize_drm =====
yamllint OK.
ansible-lint OK.

===== IMPORTING ROLE: accelize_drm =====

Updating repository versions...
Import completed with 0 warnings and 0 errors
```

We should probably do a case insensitive lookup here:  https://github.com/ansible/galaxy/blob/devel/galaxy/api/views/views.py#L389 And raise an exception when no match is found.
