### ISSUE TITLE
Galaxy Fetch Fails When Tilde (~) Is Part of Dependency Filename

### ISSUE THREAD

**Issue by imareporter** [ansible/galaxy#2456]
##### SUMMARY

When a file in a role has a tilde (`~`) in the name, the `ansible-galaxy` pull fails.

##### STEPS TO REPRODUCE

When filename does not contain a tilde (`~`):

~~~
[root@0b37f81e0ac0 galaxy]# ansible-galaxy install -r requirements.yml -vvv
ansible-galaxy 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
Reading requirement file at 'requirements.yml'
found role {'scm': 'git', 'src': 'http://git.example.com/ansible/tester.git', 'version': '', 'name': 'tester'} in yaml file
Processing role tester 
archiving ['/usr/bin/git', 'archive', '--prefix=tester/', u'--output=/root/.ansible/tmp/ansible-local-8920yXDh66/tmp7Myv3l.tar', 'HEAD']
- extracting tester to /root/.ansible/roles/tester
- tester was installed successfully
[WARNING]: Meta file /root/.ansible/roles/tester is empty. Skipping dependencies.
~~~

When filename contains a tilde (`~`):

~~~
ansible-galaxy 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /etc/ansible/ansible.cfg as config file
Reading requirement file at 'requirements.yml'
found role {'scm': 'git', 'src': 'http://git.example.com/ansible/tester.git', 'version': '', 'name': 'tester'} in yaml file
Processing role tester 
archiving ['/usr/bin/git', 'archive', '--prefix=tester/', u'--output=/root/.ansible/tmp/ansible-local-8984bfuVM3/tmp_wXxbO.tar', 'HEAD']
- extracting tester to /root/.ansible/roles/tester
ERROR! Unexpected Exception, this is probably a bug: [Errno 21] Is a directory: u'/root/.ansible/roles/tester/files'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 123, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 375, in run
    context.CLIARGS['func']()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 891, in execute_install
    installed = role.install()
  File "/usr/lib/python2.7/site-packages/ansible/galaxy/role.py", line 330, in install
    role_tar_file.extract(member, self.path)
  File "/usr/lib64/python2.7/tarfile.py", line 2084, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib64/python2.7/tarfile.py", line 2160, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib64/python2.7/tarfile.py", line 2200, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 21] Is a directory: u'/root/.ansible/roles/tester/files'
~~~

##### EXPECTED RESULTS

I would think roles should be able to accommodate tildes in the filenames. 

See: https://github.com/ansible/galaxy/issues/704

**Comment by imareporter** [comment]
Moved to https://github.com/ansible/ansible/issues/71624
