### ISSUE TITLE
Installing collection by local path looks for "ole" instead of "role" folder when path includes trailing `/`

### ISSUE THREAD

**Issue by RafalSkolasinski** [ansible/galaxy#2727]
##### SUMMARY

When trying to install locally clone [collection of ours](https://github.com/SeldonIO/ansible-k8s-collection) by providing a path
```
ansible-galaxy collection install ansible-k8s-collection/ --force
```
it fails. 

It does work fine if I first `cd` into the folder and do
```
ansible-galaxy collection install . --force
```

as well as when installing from github directly with
```
ansible-galaxy collection install git+https://github.com/SeldonIO/ansible-k8s-collection.git
```

Note: when filing the issue I realise that it fails when path includes a trailing `/` so updated the title accordingly

##### STEPS TO REPRODUCE

1. Install ansible 4.1.0
2. Git clone https://github.com/SeldonIO/ansible-k8s-collection repository
3. Install collection with `ansible-galaxy collection install ansible-k8s-collection/`

##### EXPECTED RESULTS

It ignores trailing `/`

##### ACTUAL RESULTS

```
$ ansible-galaxy collection install ansible-k8s-collection/ --force -vvv
ansible-galaxy [core 2.11.1] 
  config file = None
  configured module search path = ['/home/rskolasinski/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rskolasinski/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/ansible
  ansible collection location = /home/rskolasinski/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rskolasinski/.asdf/installs/python/3.8.5/bin/ansible-galaxy
  python version = 3.8.5 (default, Jun  4 2021, 20:08:16) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
No config file found; using defaults
Starting galaxy collection install process
Found installed collection community.kubernetes:1.2.1 at '/home/rskolasinski/.ansible/collections/ansible_collections/community/kubernetes'
Found installed collection community.docker:1.7.0 at '/home/rskolasinski/.ansible/collections/ansible_collections/community/docker'
Found installed collection seldonio.ecosystem:0.1.0 at '/home/rskolasinski/.ansible/collections/ansible_collections/seldonio/ecosystem'
Found installed collection seldonio.k8s:0.1.0 at '/home/rskolasinski/.ansible/collections/ansible_collections/seldonio/k8s'
Process install dependency map
Opened /home/rskolasinski/.ansible/galaxy_token
Starting collection install process
Installing 'seldonio.k8s:0.1.0' to '/home/rskolasinski/.ansible/collections/ansible_collections/seldonio/k8s'
Skipping 'ansible-k8s-collection/.git' for collection build
Skipping 'ansible-k8s-collection/galaxy.yml' for collection build
ERROR! Unexpected Exception, this is probably a bug: [Errno 2] No such file or directory: b'ansible-k8s-collection/oles/metallb'
the full traceback was:

Traceback (most recent call last):
  File "/home/rskolasinski/.asdf/installs/python/3.8.5/bin/ansible-galaxy", line 135, in <module>
    exit_code = cli.run()
  File "/home/rskolasinski/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 552, in run
    return context.CLIARGS['func']()
  File "/home/rskolasinski/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 75, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/home/rskolasinski/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 1186, in execute_install
    self._execute_install_collection(
  File "/home/rskolasinski/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/ansible/cli/galaxy.py", line 1213, in _execute_install_collection
    install_collections(
  File "/home/rskolasinski/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/ansible/galaxy/collection/__init__.py", line 538, in install_collections
    install(concrete_coll_pin, output_path, artifacts_manager)
  File "/home/rskolasinski/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/ansible/galaxy/collection/__init__.py", line 1079, in install
    install_src(collection, b_artifact_path, b_collection_path, artifacts_manager)
  File "/home/rskolasinski/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/ansible/galaxy/collection/__init__.py", line 1160, in install_src
    collection_output_path = _build_collection_dir(
  File "/home/rskolasinski/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/ansible/galaxy/collection/__init__.py", line 1005, in _build_collection_dir
    existing_is_exec = os.stat(src_file).st_mode & stat.S_IXUSR
FileNotFoundError: [Errno 2] No such file or directory: b'ansible-k8s-collection/oles/metallb'
```

**Comment by jmighion** [comment]
This also seems to break the documentation's example for installing from a directory : 
https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-a-collection-from-source-files
Those also have the trailing slash and causes the same error.

**Comment by joeashcraft** [comment]
I ran in to this issue with ansible 2.13.3 installing from a local path

```shell
$ ansible-galaxy collection install ~/src/home_lab/
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'jta2.homelab:1.0.0' to '/home/joe/.ansible/collections/ansible_collections/jta2/homelab'
ERROR! Unexpected Exception, this is probably a bug: [Errno 2] No such file or directory: b'/home/joe/src/home_lab/laybooks/netutil.yml'
to see the full traceback, use -vvv
```
```shell
$ cat ~/.ansible/collections/ansible_collections/jta2/homelab/FILES.json
{
 "files": [
  {
   "name": ".",
   "ftype": "dir",
   "chksum_type": null,
   "chksum_sha256": null,
   "format": 1
  },
  {
   "name": "README.md",
   "ftype": "file",
   "chksum_type": "sha256",
   "chksum_sha256": "a4c55a8bc1f5bb8f9a1acb580daa2940f68a5fdae3d281340b40c432a0726d33",
   "format": 1
  },
  {
   "name": ".gitlab-ci.yml",
   "ftype": "file",
   "chksum_type": "sha256",
   "chksum_sha256": "11be0240a44b927cd7eeff05ad7a4b2807c6287bab42c3aa6c7f1cea8bb8601d",
   "format": 1
  },
  {
   "name": "docs",
   "ftype": "dir",
   "chksum_type": null,
   "chksum_sha256": null,
   "format": 1
  },
  {
   "name": "plugins",
   "ftype": "dir",
   "chksum_type": null,
   "chksum_sha256": null,
   "format": 1
  },
  {
   "name": "lugins/README.md",
   "ftype": "file",
   "chksum_type": "sha256",
   "chksum_sha256": "23e9939164cad964c2338b8059e4d3def72eef9523e32594503efd50960fcae4",
   "format": 1
  },
...
```
```shell
$ ansible-galaxy --version
ansible-galaxy [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/joe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/joe/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-galaxy
  python version = 3.9.14 (main, Jan  9 2023, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```
