### ISSUE TITLE
ERROR while installing role from GitHub with requirements.yaml

### ISSUE THREAD

**Issue by florian-hild** [ansible/galaxy#2873]
##### STEPS TO REPRODUCE
`ansible-galaxy install -r requirements.yaml -vvv`

##### ACTUAL RESULTS
I got this Error, but the role was installed.

```
test@vm:$ ansible-galaxy install -r requirements.yaml -vvv
ansible-galaxy [core 2.12.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/hild/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/hild/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-galaxy
  python version = 3.10.1 (main, Dec 11 2021, 17:22:55) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
Reading requirement file at '/home/hild/git_repos/ansible/roles_dev/requirements.yaml'
found role {'name': 'setup-dns-config', 'src': 'git@github.com:mycompany/ansible-role-setup-dns-config.git', 'scm': 'git', 'version': 'main'} in yaml file
Opened /home/hild/.ansible/galaxy_token
Starting galaxy role install process
Processing role setup-dns-config
archiving ['/usr/bin/git', 'archive', '--prefix=setup-dns-config/', '--output=/home/test/.ansible/tmp/ansible-local-3176906p757_yhu/tmp_au0c4pt.tar', 'main']
- extracting setup-dns-config to /etc/ansible/galaxy_roles/setup-dns-config
- setup-dns-config (main) was installed successfully
None <-- Included prints for debuging ( print(role.requirements))
None <-- Included prints for debuging ( print(role.metadata.get('dependencies')))
ERROR! Unexpected Exception, this is probably a bug: can only concatenate list (not "NoneType") to list
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 128, in <module>
    exit_code = cli.run()
  File "/usr/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 567, in run
    return context.CLIARGS['func']()
  File "/usr/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 86, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 1195, in execute_install
    self._execute_install_role(role_requirements)
  File "/usr/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 1282, in _execute_install_role
    role_dependencies = (role.metadata.get('dependencies') or []) + role.requirements
TypeError: can only concatenate list (not "NoneType") to list
```

```
$ cat requirements.yaml
---

- name: setup-dns-config
  src: git@github.com:mycompany/ansible-role-setup-dns-config.git
  scm: git
  version: main
```

**Comment by florian-hild** [comment]
I found the problem.

There was an empty meta/requirements.yml file in the role repo.
