### ISSUE TITLE
ansible-galaxy fails on installing a module

### ISSUE THREAD

**Issue by tdominguezm** [ansible/galaxy#2977]
##### SUMMARY

I encountered this by trying to install community.general.timezone module using ansible galaxy, it outputs a syntax error, but even using the command alone outputs the same error.

STEPS TO REPRODUCE

`ansible-galaxy` or `ansible-galaxy collection install community.general`

##### EXPECTED RESULTS

It installs the community.general module or outputs something other than an error
##### ACTUAL RESULTS

It outputs a python syntax error.

```

ERROR! Unexpected Exception, this is probably a bug: invalid syntax (core.py, line 17)
the full traceback was:

Traceback (most recent call last):
  File "/bin/ansible-galaxy", line 92, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 24, in <module>
    from ansible.galaxy.api import GalaxyAPI
  File "/usr/lib/python2.7/site-packages/ansible/galaxy/api.py", line 22, in <module>
    from ansible.module_utils.urls import open_url
  File "/usr/lib/python2.7/site-packages/ansible/module_utils/urls.py", line 101, in <module>
    from requests.packages.urllib3.contrib.pyopenssl import PyOpenSSLContext
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 133, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 27, in <module>
    from . import certs
  File "/usr/lib/python2.7/site-packages/requests/certs.py", line 15, in <module>
    from certifi import where
  File "/usr/lib/python2.7/site-packages/certifi/__init__.py", line 1, in <module>
    from .core import contents, where
  File "/usr/lib/python2.7/site-packages/certifi/core.py", line 17
    def where() -> str:
                ^
SyntaxError: invalid syntax

```

**Comment by s-hertel** [comment]
Python 2.7 has not been supported since ansible-galaxy 2.11. See the `Controller Python` column of https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix  for the versions of Python that can be used with your version of `ansible-galaxy`.

In the future, please file issues for ansible-galaxy at https://github.com/ansible/ansible where it is maintained. This repo is only for https://galaxy.ansible.com/.
