### ISSUE TITLE
Unexpected Exception when updating Ansible Collection with already satisfied dependencies

### ISSUE THREAD

**Issue by MonolithProjects** [ansible/galaxy#3015]
##### SUMMARY
When installing Ansible Collection which has already all dependencies satisfied (deps are already installed and in the required version), the `ansible-galaxy collection install` will fail with error:
```ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object has no attribute 'items'```
 As a workaround i have to either use the option `--no-deps` or delete the already preinstalled collection dependencies (at least one).

##### STEPS TO REPRODUCE
I will install ansible collection `lablabs.wireguard:0.2.2` which will install also the dependencies. Then i will try to upgrade the collection to `lablabs.wireguard:0.2.3`. Both Collections have the dependencies in `galaxy.yaml` with the same version:
```
dependencies:
  devsec.hardening: "7.12.0"
  robertdebock.development_environment: "2.1.1"
```
Commands to reproduce:
```bash
   ansible-galaxy --version
ansible-galaxy [core 2.13.4]
  config file = None
  configured module search path = ['/home/mike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mike/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/mike/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mike/.local/bin/ansible-galaxy
  python version = 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
  jinja version = 3.0.3
  libyaml = False

   rm -rf /home/mike/.ansible/collections

   ansible-galaxy collection install lablabs.wireguard:0.2.2
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/lablabs-wireguard-0.2.2.tar.gz to /home/mike/.ansible/tmp/ansible-local-98923ojylfd0v/tmp803o3d0a/lablabs-wireguard-0.2.2-4458scwh
Downloading https://galaxy.ansible.com/download/devsec-hardening-7.12.0.tar.gz to /home/mike/.ansible/tmp/ansible-local-98923ojylfd0v/tmp803o3d0a/devsec-hardening-7.12.0-t4n1pwso
Installing 'lablabs.wireguard:0.2.2' to '/home/mike/.ansible/collections/ansible_collections/lablabs/wireguard'
lablabs.wireguard:0.2.2 was installed successfully
Installing 'devsec.hardening:7.12.0' to '/home/mike/.ansible/collections/ansible_collections/devsec/hardening'
Downloading https://galaxy.ansible.com/download/robertdebock-development_environment-2.1.1.tar.gz to /home/mike/.ansible/tmp/ansible-local-98923ojylfd0v/tmp803o3d0a/robertdebock-development_environment-2.1.1-_xvyu0t1
devsec.hardening:7.12.0 was installed successfully
Installing 'robertdebock.development_environment:2.1.1' to '/home/mike/.ansible/collections/ansible_collections/robertdebock/development_environment'
Downloading https://galaxy.ansible.com/download/ansible-posix-1.4.0.tar.gz to /home/mike/.ansible/tmp/ansible-local-98923ojylfd0v/tmp803o3d0a/ansible-posix-1.4.0-5ud5y1v8
robertdebock.development_environment:2.1.1 was installed successfully
Downloading https://galaxy.ansible.com/download/community-mysql-3.5.1.tar.gz to /home/mike/.ansible/tmp/ansible-local-98923ojylfd0v/tmp803o3d0a/community-mysql-3.5.1-008ol9_7
Installing 'ansible.posix:1.4.0' to '/home/mike/.ansible/collections/ansible_collections/ansible/posix'
ansible.posix:1.4.0 was installed successfully
Installing 'community.mysql:3.5.1' to '/home/mike/.ansible/collections/ansible_collections/community/mysql'
Downloading https://galaxy.ansible.com/download/community-crypto-2.7.0.tar.gz to /home/mike/.ansible/tmp/ansible-local-98923ojylfd0v/tmp803o3d0a/community-crypto-2.7.0-rbxaksy0
community.mysql:3.5.1 was installed successfully
Installing 'community.crypto:2.7.0' to '/home/mike/.ansible/collections/ansible_collections/community/crypto'
Downloading https://galaxy.ansible.com/download/community-general-5.7.0.tar.gz to /home/mike/.ansible/tmp/ansible-local-98923ojylfd0v/tmp803o3d0a/community-general-5.7.0-oo6ik4h0
community.crypto:2.7.0 was installed successfully
Installing 'community.general:5.7.0' to '/home/mike/.ansible/collections/ansible_collections/community/general'
community.general:5.7.0 was installed successfully

   ansible-galaxy collection install lablabs.wireguard:0.2.3 -vvv
ansible-galaxy [core 2.13.4]
  config file = None
  configured module search path = ['/home/mike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mike/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/mike/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mike/.local/bin/ansible-galaxy
  python version = 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
  jinja version = 3.0.3
  libyaml = False
No config file found; using defaults
Starting galaxy collection install process
Found installed collection robertdebock.development_environment:2.1.1 at '/home/mike/.ansible/collections/ansible_collections/robertdebock/development_environment'
Found installed collection devsec.hardening:7.12.0 at '/home/mike/.ansible/collections/ansible_collections/devsec/hardening'
Found installed collection lablabs.wireguard:0.2.2 at '/home/mike/.ansible/collections/ansible_collections/lablabs/wireguard'
Found installed collection ansible.posix:1.4.0 at '/home/mike/.ansible/collections/ansible_collections/ansible/posix'
Found installed collection community.crypto:2.7.0 at '/home/mike/.ansible/collections/ansible_collections/community/crypto'
Found installed collection community.general:5.7.0 at '/home/mike/.ansible/collections/ansible_collections/community/general'
Found installed collection community.mysql:3.5.1 at '/home/mike/.ansible/collections/ansible_collections/community/mysql'
Process install dependency map
Opened /home/mike/.ansible/galaxy_token
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object has no attribute 'items'
the full traceback was:

Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/cli/__init__.py", line 601, in cli_executor
    exit_code = cli.run()
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 652, in run
    return context.CLIARGS['func']()
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 102, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 1311, in execute_install
    self._execute_install_collection(
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 1348, in _execute_install_collection
    install_collections(
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/galaxy/collection/__init__.py", line 705, in install_collections
    dependency_map = _resolve_depenency_map(
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/galaxy/collection/__init__.py", line 1637, in _resolve_depenency_map
    return collection_dep_resolver.resolve(
  File "/home/mike/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/mike/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 347, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/home/mike/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/home/mike/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/galaxy/dependency_resolution/providers.py", line 486, in get_dependencies
    for dep_name, dep_req in req_map.items()
AttributeError: 'NoneType' object has no attribute 'items'
```

##### EXPECTED RESULTS
`ansible-galaxy collection install` will not fail when all dependency are already installed

##### ACTUAL RESULTS
`ansible-galaxy collection install` for a collection which has the dependency satisfied is failing. As a workaround i have to ether use option `--no-deps` or delete the preinstalled collections.
```
  ansible-galaxy collection install lablabs.wireguard:0.2.3 -vvv
ansible-galaxy [core 2.13.4]
  config file = None
  configured module search path = ['/home/mike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mike/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/mike/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mike/.local/bin/ansible-galaxy
  python version = 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
  jinja version = 3.0.3
  libyaml = False
No config file found; using defaults
Starting galaxy collection install process
Found installed collection robertdebock.development_environment:2.1.1 at '/home/mike/.ansible/collections/ansible_collections/robertdebock/development_environment'
Found installed collection devsec.hardening:7.12.0 at '/home/mike/.ansible/collections/ansible_collections/devsec/hardening'
Found installed collection lablabs.wireguard:0.2.2 at '/home/mike/.ansible/collections/ansible_collections/lablabs/wireguard'
Found installed collection ansible.posix:1.4.0 at '/home/mike/.ansible/collections/ansible_collections/ansible/posix'
Found installed collection community.crypto:2.7.0 at '/home/mike/.ansible/collections/ansible_collections/community/crypto'
Found installed collection community.general:5.7.0 at '/home/mike/.ansible/collections/ansible_collections/community/general'
Found installed collection community.mysql:3.5.1 at '/home/mike/.ansible/collections/ansible_collections/community/mysql'
Process install dependency map
Opened /home/mike/.ansible/galaxy_token
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object has no attribute 'items'
the full traceback was:

Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/cli/__init__.py", line 601, in cli_executor
    exit_code = cli.run()
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 652, in run
    return context.CLIARGS['func']()
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 102, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 1311, in execute_install
    self._execute_install_collection(
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 1348, in _execute_install_collection
    install_collections(
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/galaxy/collection/__init__.py", line 705, in install_collections
    dependency_map = _resolve_depenency_map(
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/galaxy/collection/__init__.py", line 1637, in _resolve_depenency_map
    return collection_dep_resolver.resolve(
  File "/home/mike/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/mike/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 347, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/home/mike/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 207, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/home/mike/.local/lib/python3.10/site-packages/resolvelib/resolvers.py", line 198, in _get_criteria_to_update
    for r in self._p.get_dependencies(candidate):
  File "/home/mike/.local/lib/python3.10/site-packages/ansible/galaxy/dependency_resolution/providers.py", line 486, in get_dependencies
    for dep_name, dep_req in req_map.items()
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by Thumbiceq** [comment]
I hit exactly the same issue with `ansible-galaxy collection install ...` 

When upgrading collection and all dependencies are already installed it fails with `ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object has no attribute 'items'`

**Comment by MonolithProjects** [comment]
Since this is not related to `ansible/galaxy` but to `ansible/ansible` i am closing this issue and will open a new one in correct repository.
