### ISSUE TITLE
Incorrect Documentation/Possible Feature Regression: Git Commit Hashes/Branch Names as Version

### ISSUE THREAD

**Issue by aarongoulet** [ansible/galaxy#3121]
##### SUMMARY
Documentation for supported version syntaxes is no longer correct.  This may be an unintended regression, or it may have been done intentionally and the documentation was never updated to reflect it.  The documentation in question is [here](https://github.com/ansible/galaxy/blame/devel/docs/docsite/rst/using/installing.rst#L103-L105):

> version:
> The version of the role to download. Provide a tag value, commit hash, or branch name.
> Defaults to *master*.

##### STEPS TO REPRODUCE
In `requirements.yml`:

```yaml
  # Install an internal collection via git.
  - name: my.collection
    version: f2897d7b8538ffb12d1eeda64fabd5f0c1cdb5fb
    source: git+ssh://git@gitlab.mycompany.com/aarongoulet/my-collection.git
    type: git
```

CLI command:
`ansible-galaxy collection install -U -r requirements.yml`

##### EXPECTED RESULTS
Successful collection installation/update.

##### ACTUAL RESULTS

```
ERROR! Unexpected Exception, this is probably a bug: Non integer values in LooseVersion ('34ba4227ccdd62b440c3ef58ea043292d27c052c')
the full traceback was:

Traceback (most recent call last):
  File "/home/aaron.goulet/.local/lib/python3.10/site-packages/ansible/cli/__init__.py", line 647, in cli_executor
    exit_code = cli.run()
  File "/home/aaron.goulet/.local/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 711, in run
    return context.CLIARGS['func']()
  File "/home/aaron.goulet/.local/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 118, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/home/aaron.goulet/.local/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 1360, in execute_install
    self._execute_install_collection(
  File "/home/aaron.goulet/.local/lib/python3.10/site-packages/ansible/cli/galaxy.py", line 1397, in _execute_install_collection
    install_collections(
  File "/home/aaron.goulet/.local/lib/python3.10/site-packages/ansible/galaxy/collection/__init__.py", line 697, in install_collections
    unsatisfied_requirements -= set() if force or force_deps else {
  File "/home/aaron.goulet/.local/lib/python3.10/site-packages/ansible/galaxy/collection/__init__.py", line 701, in <setcomp>
    if req.fqcn == exs.fqcn and meets_requirements(exs.ver, req.ver)
  File "/home/aaron.goulet/.local/lib/python3.10/site-packages/ansible/galaxy/dependency_resolution/versioning.py", line 63, in meets_requirements
    SemanticVersion.from_loose_version(LooseVersion(requirement)),
  File "/home/aaron.goulet/.local/lib/python3.10/site-packages/ansible/utils/version.py", line 178, in from_loose_version
    raise ValueError("Non integer values in %r" % loose_version)
ValueError: Non integer values in LooseVersion ('34ba4227ccdd62b440c3ef58ea043292d27c052c')
```

**Comment by aarongoulet** [comment]
I should add that it works fine if I create a tag with a semantic version, e.g. "1.0.0".

**Comment by isuftin** [comment]
I've been battling the same issue today. What worked is...

```yaml
  - name: community.zabbix
    source: git+https://my.repo.location/automation/ansible/collections/community-zabbix/,df1dd905cab0866a5bca16077f7fbf3eae9a9c9e
    type: git
```

But yeah, according to the docs, there should be no issue specifying the specific commit in the version parameter :/

**Comment by s-hertel** [comment]
Please file issues for ansible-galaxy at https://github.com/ansible/ansible where it is maintained. This repo is only for https://galaxy.ansible.com/.
