### ISSUE TITLE
Traceback occurs when installing a role without sudo

### ISSUE THREAD

**Issue by thedrow** [ansible/galaxy#400]
When attempting to install debops.fail2ban I get the following traceback:
```
ansible-galaxy install debops.fail2ban -vvv
ansible-galaxy 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/omer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: Unable to set correct type for configuration entry: DEFAULT_LOCAL_TMP

Opened /home/omer/.ansible_galaxy
Processing role debops.fail2ban 
Opened /home/omer/.ansible_galaxy
- downloading role 'fail2ban', owned by debops
https://galaxy.ansible.com/api/v1/roles/?owner__username=debops&name=fail2ban
https://galaxy.ansible.com/api/v1/roles/3377/versions/?page_size=50
- downloading role from https://github.com/debops/ansible-fail2ban/archive/v0.1.2.tar.gz
- extracting debops.fail2ban to /home/omer/.ansible/roles/debops.fail2ban
- extracting debops.fail2ban to /usr/share/ansible/roles/debops.fail2ban
- extracting debops.fail2ban to /etc/ansible/roles/debops.fail2ban
ERROR! Unexpected Exception, this is probably a bug: list index out of range
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 150, in run
    self.execute()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 393, in execute_install
    installed = role.install()
  File "/usr/lib/python2.7/dist-packages/ansible/galaxy/role.py", line 333, in install
    self.path = self.paths[current + 1]
IndexError: list index out of range
```

When using `sudo ansible-galaxy install debops.fail2ban` everything works as expected.
The traceback does not indicate what the true problem is.

**Comment by dabcoder** [comment]
Also ran into this issue when trying to install a role on CentOS 7
