### ISSUE TITLE
'ansible-galaxy install alikins.alikins_test1' against 3.0 throws client JSON error and server  ValueError

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy#454]
running the stable-2.5 version 'ansible-galaxy install' against 337a0a4 (release/3.0 branch) fails.

`ansible-galaxy -vvv -s http://localhost:8000 install alikins.alikins_test`

client tracebacks with a ValueError in JSON decode
server logs a ValueError: ValueError: invalid literal for int() with base 10: 'alikins'

```
(galaxy-py27) [newswoop:F27:galaxy (test_ansible-galaxy %)]$ ansible-galaxy -vvv -s http://localhost:8000 install alikins.alikins_test1
ansible-galaxy 2.5.0 (stable-2.5 5f98ee878e) last updated 2018/04/12 15:43:48 (GMT -400)
  config file = None
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible-galaxy
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
No config file found; using defaults
Opened /home/adrian/.ansible_galaxy
Processing role alikins.alikins_test1 
Opened /home/adrian/.ansible_galaxy
- downloading role 'alikins_test1', owned by alikins
http://localhost:8000/api/v1/roles/?owner__username=alikins&name=alikins_test1
ERROR! Unexpected Exception, this is probably a bug: No JSON object could be decoded
the full traceback was:

Traceback (most recent call last):
  File "/home/adrian/src/ansible/bin/ansible-galaxy", line 118, in <module>
    exit_code = cli.run()
  File "/home/adrian/src/ansible/lib/ansible/cli/galaxy.py", line 150, in run
    self.execute()
  File "/home/adrian/src/ansible/lib/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/home/adrian/src/ansible/lib/ansible/cli/galaxy.py", line 393, in execute_install
    installed = role.install()
  File "/home/adrian/src/ansible/lib/ansible/galaxy/role.py", line 214, in install
    role_data = api.lookup_role_by_name(self.src)
  File "/home/adrian/src/ansible/lib/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/home/adrian/src/ansible/lib/ansible/galaxy/api.py", line 193, in lookup_role_by_name
    data = self.__call_galaxy(url)
  File "/home/adrian/src/ansible/lib/ansible/galaxy/api.py", line 56, in wrapped
    return method(self, *args, **kwargs)
  File "/home/adrian/src/ansible/lib/ansible/galaxy/api.py", line 96, in __call_galaxy
    res = json.loads(to_text(e.fp.read(), errors='surrogate_or_strict'))
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

The server logs:

```
2018-04-12 15:53:45,672 369:Thread-30 ERROR galaxy.api.throttling throttling.py allow_request:64 : Error finding role alikins.alikin
s_test1 - ("invalid literal for int() with base 10: 'alikins'",)
2018-04-12 15:53:45,672 369:Thread-30 ERROR django.request exception.py handle_uncaught_exception:135 : Internal Server Error: /api/
v1/roles/
Traceback (most recent call last):
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/galaxy/galaxy/api/views/roles.py", line 54, in list
    qs = qs.filter(**params)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'alikins'
```

**Comment by alikins** [comment]
Not sure if it's related, but after that, I don't seem to be able to view my test content any more.  Nothing in the main page (in the 'app-container' div ) seems to load. For my logged in user via chrome or via a not-logged in visit in firefox.

Don't see much in the server logs, but the stuff after the above traceback:

```
2018-04-12 15:53:45,756 369:Thread-30 ERROR django.server basehttp.py log_message:124 : "GET /api/v1/roles/?owner__username=alikins&
name=alikins_test1 HTTP/1.1" 500 21791
2018-04-12 15:53:48,525 369:Thread-31 INFO django.server basehttp.py log_message:124 : "GET /api/v1/repositories/?provider_namespace
__id=1&page_size=1000 HTTP/1.1" 200 2552
2018-04-12 15:53:58,525 369:Thread-32 INFO django.server basehttp.py log_message:124 : "GET /api/v1/repositories/?provider_namespace
__id=1&page_size=1000 HTTP/1.1" 200 2552
^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A2018-04-12 15:54:08,531 369:Thread-33 INFO django.server basehttp.py log_message:124
 : "GET /api/v1/repositories/?provider_namespace__id=1&page_size=1000 HTTP/1.1" 200 2552
2018-04-12 15:54:18,534 369:Thread-34 INFO django.server basehttp.py log_message:124 : "GET /api/v1/repositories/?provider_namespace
__id=1&page_size=1000 HTTP/1.1" 200 2552
```

Screenshot from chrome:
![screenshot] 
(https://imgur.com/a/spicN)

**Comment by alikins** [comment]
'ansible-galaxy -vvv -s http://localhost:8000 info alikins.alikins_test1' fails in similar fashion.

**Comment by chouseknecht** [comment]
Well, `http://localhost:8000/api/v1/roles/?owner__username=alikins&name=alikins_test1` could be a problem. There is no longer an `owner` associated with a role. We'll need to intercept this query, and translate it into something that works.

Looks like we're doing that already [here in api/views/roles.py](https://github.com/ansible/galaxy/blob/release/3.0/galaxy/api/views/roles.py#L46), which is the API view that responds to any request sent to /api/v1/roles.

**Comment by alikins** [comment]
http://localhost:8000/api/v1/content/?repository__name=testing-content&namespace__name=alikins  seems to work
