### ISSUE TITLE
'ansible-galaxy import' against 3.0 server cause client error: KeyError: u'DEBUG'

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy#455]
Running `ansible-galaxy import alikins alikins_test1` against a 3.0 server (337a0a446e97ba6f7c9dd5bc02ec9b03310e9653) causes the client to
throw a KeyError, but it looks like the server side operation worked.

Note: The KeyError is likely a client bug, possibly obscuring another error, but 
referencing it here and in subject so it's easier to find. Haven't dug into the client
error yet.

```
(galaxy-py27) [newswoop:F27:galaxy (test_ansible-galaxy %)]$ ansible-galaxy -vvv -s http://localhost:8000 import alikins ansible-role-alikins_test1
ansible-galaxy 2.4.4.0 (stable-2.4 00348c3db0) last updated 2018/04/12 16:42:12 (GMT -400)
  config file = None
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible-galaxy
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
No config file found; using defaults
Opened /home/adrian/.ansible_galaxy
http://localhost:8000/api/v1/imports/
Successfully submitted import request 44
http://localhost:8000/api/v1/imports/?id=44
INFO Starting import: task_id=44, repository=alikins/ansible-role-alikins_test1
http://localhost:8000/api/v1/imports/?id=44
ERROR! Unexpected Exception, this is probably a bug: u'DEBUG'
the full traceback was:

Traceback (most recent call last):
  File "/home/adrian/src/ansible/bin/ansible-galaxy", line 106, in <module>
    exit_code = cli.run()
  File "/home/adrian/src/ansible/lib/ansible/cli/galaxy.py", line 150, in run
    self.execute()
  File "/home/adrian/src/ansible/lib/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/home/adrian/src/ansible/lib/ansible/cli/galaxy.py", line 613, in execute_import
    display.display(msg['message_text'], color=colors[msg['message_type']])
KeyError: u'DEBUG'
```

The import itself seemed to work however. No errors in celery or http logs, and the imported role shows up at http://localhost:8000/my-imports?namespace=alikins&repository_name=alikins_test1

**Comment by alikins** [comment]
I think this is an ansible/ansible or ansible/galaxy-cli bug as well.

The two components are:

1. for import tasks, galaxy server side import tasks ImportTaskMessage can end up with the message type set of DEBUG (via the galaxy.common.logutils.ImportTaskHandler and galaxy.constants.ImportTaskMessageType.from_logging_level) if the import task logging is at DEBUG.

2. in current ansible/ansible or ansible/galaxy-cli when doing an 'import' action the client polls for the task import status and trys to display the /api/v1/imports/N objects task_messages and colorize the result based on the messages message_type. But the 'colors' dict that maps message_type to display color doesnt have a DEBUG entry, so if (1) happens, the client will traceback.

ansible/galaxy-cli has a fix for (2) https://github.com/ansible/galaxy-cli/commit/699c2d7e1c6d94fd00842f844e9a4f60e8688277 but 'ansible-galaxy' in ansible/ansible does not yet. 

But can avoid the error with just galaxy side workaround by either not logging task imports at DEBUG level, or could filter it  out.

Since it requires DEBUG level server logging to trigger and there is a client fix in galaxy-cli, this is low priority.
