### ISSUE TITLE
POST to /api/v1/imports (for a repo that doesnt exist) causes celery import task to prompt for username to celeryd stdout

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy#490]
Using a v3 galaxy server, and the galaxy-cli with command:

`python bin/ansible-galaxy-cli  -vvv -s http://localhost:8000 import alikins test-role-1`

The server side celeryd ended up prompting for github auth at it's console. 

**Note: There is no 'test-role-1' repo**

This was after having done some switching back and forth between being authenticated  to galaxy.ansible.com via 'ansible-galaxy login' and connecting to my localhost server.
So possible the github auth sent to localhost v3 server was the incorrect token. But I suspect
it's more related to 'test-role-1' not existing.

client output/log
```
(galaxy-py27) [newswoop:F27:ansible-galaxy-cli (land_galaxy_client %)]$ python bin/ansible-galaxy-cli  -vvv -s http://localhost:8000 import alikins test-role-1
[11:08:24,300 03134 I] ansible_galaxy_cli.cli run:160 - No config file found; using defaults
[11:08:24,300 03134 I] ansible_galaxy.flat_rest_api.token.GalaxyToken __open_config_for_read:46 - Opened /home/adrian/.ansible_galaxy
[11:08:24,301 03134 D] ansible_galaxy.flat_rest_api.api.GalaxyAPI __init__:74 - Validate TLS certificates: True
[11:08:24,301 03134 D] ansible_galaxy.flat_rest_api.api wrapped:46 - Initial connection to galaxy_server: http://localhost:8000
[11:08:24,307 03134 D] ansible_galaxy.flat_rest_api.api wrapped:53 - Base API: http://localhost:8000/api/v1
[11:08:24,307 03134 I] ansible_galaxy.flat_rest_api.api.GalaxyAPI __call_galaxy:91 - http://localhost:8000/api/v1/imports/
Successfully submitted import request 4
[11:08:24,353 03134 I] ansible_galaxy.flat_rest_api.api.GalaxyAPI __call_galaxy:91 - http://localhost:8000/api/v1/imports/?id=4
INFO Starting import: task_id=4, repository=alikins/test-role-1
[11:08:34,393 03134 I] ansible_galaxy.flat_rest_api.api.GalaxyAPI __call_galaxy:91 - http://localhost:8000/api/v1/imports/?id=4
[11:08:44,449 03134 I] ansible_galaxy.flat_rest_api.api.GalaxyAPI __call_galaxy:91 - http://localhost:8000/api/v1/imports/?id=4

# <snipped many repeats of previous line (import status check) every ten seconds until control-c'ed >
^CTraceback (most recent call last):
  File "bin/ansible-galaxy-cli", line 11, in <module>
    sys.exit(main(args=args))
  File "/home/adrian/src/ansible-galaxy-cli/ansible_galaxy_cli/main.py", line 22, in main
    res = cli.run()
  File "/home/adrian/src/ansible-galaxy-cli/ansible_galaxy_cli/cli/galaxy.py", line 165, in run
    self.execute()
  File "/home/adrian/src/ansible-galaxy-cli/ansible_galaxy_cli/cli/__init__.py", line 144, in execute
    fn()
  File "/home/adrian/src/ansible-galaxy-cli/ansible_galaxy_cli/cli/galaxy.py", line 778, in execute_import
    time.sleep(10)
KeyboardInterrupt
```

celeryd service log
```
2018-04-26 11:08:24,352 INFO tasks: Starting task: 4
[2018-04-26 11:08:24,352: INFO/Worker-9] Starting task: 4
Username for 'https://github.com':   
Password for 'https://github.com': 

< note:   after ctrl-c of client, just <enter>, <enter> here (bogus github auth)  >

remote: Repository not found.
fatal: Authentication failed for 'https://github.com/alikins/test-role-1.git/'
2018-04-26 11:22:38,391 ERROR tasks: Command '['git', 'clone', '--quiet', '--depth', '1', 'https://github.com/alikins/test-role-1.git', '/tmp/tmpUFogvd']' return
ed non-zero exit status 128
Traceback (most recent call last):
  File "/galaxy/galaxy/worker/tasks.py", line 57, in import_repository
    _import_repository(import_task, logger)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/galaxy/galaxy/worker/tasks.py", line 89, in _import_repository
    logger=logger)
  File "/galaxy/galaxy/importer/repository.py", line 34, in import_repository
    git.clone_repository(url, clone_dir, branch=branch)
  File "/galaxy/galaxy/importer/utils/git.py", line 67, in clone_repository
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['git', 'clone', '--quiet', '--depth', '1', 'https://github.com/alikins/test-role-1.git', '/tmp/tmpUFogvd']' returned non-zero exit
status 128
[2018-04-26 11:22:38,391: ERROR/Worker-9] Command '['git', 'clone', '--quiet', '--depth', '1', 'https://github.com/alikins/test-role-1.git', '/tmp/tmpUFogvd']' r
eturned non-zero exit status 128
Traceback (most recent call last):
  File "/galaxy/galaxy/worker/tasks.py", line 57, in import_repository
    _import_repository(import_task, logger)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/galaxy/galaxy/worker/tasks.py", line 89, in _import_repository
    logger=logger)
  File "/galaxy/galaxy/importer/repository.py", line 34, in import_repository
    git.clone_repository(url, clone_dir, branch=branch)
  File "/galaxy/galaxy/importer/utils/git.py", line 67, in clone_repository
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['git', 'clone', '--quiet', '--depth', '1', 'https://github.com/alikins/test-role-1.git', '/tmp/tmpUFogvd']' returned non-zero exit  status 128
[2018-04-26 11:22:38,425: ERROR/MainProcess] Task galaxy.worker.tasks.import_repository[98cd74b9-fc31-4658-a182-5b41d7ff8c95] raised unexpected: CalledProcessError()
Traceback (most recent call last):
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/galaxy/galaxy/worker/tasks.py", line 57, in import_repository
    _import_repository(import_task, logger)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/galaxy/galaxy/worker/tasks.py", line 89, in _import_repository
    logger=logger)
  File "/galaxy/galaxy/importer/repository.py", line 34, in import_repository
    git.clone_repository(url, clone_dir, branch=branch)
  File "/galaxy/galaxy/importer/utils/git.py", line 67, in clone_repository
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError
```

galaxy/django service log
```
2018-04-26 11:05:47,111 INFO basehttp: "POST /api/v1/tokens/ HTTP/1.1" 200 73
2018-04-26 11:08:24,305 DEBUG throttling: RoleDownloadCountThrottle:
2018-04-26 11:08:24,306 INFO basehttp: "GET /api/ HTTP/1.1" 200 95
2018-04-26 11:08:24,317 DEBUG access: ImportTaskAccess.can_add (<QueryDict: {u'github_user': [u'alikins'], u'github_repo': [u'test-role-1'], u'github_reference':
 [u'']}>,) returned True
2018-04-26 11:08:24,317 DEBUG permissions: has_permission returned True
2018-04-26 11:08:24,317 DEBUG throttling: RoleDownloadCountThrottle:
2018-04-26 11:08:24,352 INFO basehttp: "POST /api/v1/imports/ HTTP/1.1" 201 898
2018-04-26 11:08:24,357 DEBUG permissions: has_permission returned True
2018-04-26 11:08:24,357 DEBUG throttling: RoleDownloadCountThrottle:
2018-04-26 11:08:24,388 INFO basehttp: "GET /api/v1/imports/?id=4 HTTP/1.1" 200 1116
2018-04-26 11:08:34,404 DEBUG permissions: has_permission returned True
2018-04-26 11:08:34,404 DEBUG throttling: RoleDownloadCountThrottle:
2018-04-26 11:08:34,437 INFO basehttp: "GET /api/v1/imports/?id=4 HTTP/1.1" 200 1116
2018-04-26 11:08:44,458 DEBUG permissions: has_permission returned True
2018-04-26 11:08:44,459 DEBUG throttling: RoleDownloadCountThrottle:
2018-04-26 11:08:44,493 INFO basehttp: "GET /api/v1/imports/?id=4 HTTP/1.1" 200 1116
2018-04-26 11:08:54,516 DEBUG permissions: has_permission returned True
2018-04-26 11:08:54,517 DEBUG throttling: RoleDownloadCountThrottle:

< note: snipped the repeats of the "GET /api/v1/imports/?id=4 HTTP/1.1" 200 1116" here>
```

**Comment by cutwater** [comment]
@alikins Thanks for reporting this issue. I'll take a look. Definitely worker should not hang on authentication when trying to clone a repository.
