### ISSUE TITLE
when using v3 search api, get a 500 ISE, NoReverseMatch: Reverse for 'role_versions_list' not found. "'role_versions_list' is not a valid view function or pattern name."

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy#520]
galaxy version: c37ed19b9acf90cebf825a457c94b22449504af2 (also tested with https://github.com/ansible/galaxy/pull/519 and same results)

when running:

   `ansible-galaxy -s http://localhost:8000 search this_is_a_search_term` 

or making the query:

 `GET http://localhost:8000//api/v1/search/roles/?&autocomplete=this_is_a_search_term&page_size=1000`

The server throws a 500 Internal Server Error with the exception:

   `NoReverseMatch: Reverse for 'role_versions_list' not found. 'role_versions_list' is not a valid view function or pattern name.`

Tracebacks and logs below.

apache style log of request

```
[11/May/2018 16:02:09] "GET /api/v1/search/roles/?&autocomplete=this_is_a_search_term&page_size=1000 HTTP/1.1" 500 23871
```

galaxy log
```
[2018-05-11 16:02:09,274 8038:Thread-26 E] django.request exception.py handle_uncaught_exception:135 : Internal Server Error: /api/v1/search/roles/
Traceback (most recent call last):
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/generics.py", line 201, in get
    return self.list(request, *args, **kwargs)
  File "/galaxy/galaxy/api/views/search.py", line 113, in list
    return self.make_response(queryset)
  File "/galaxy/galaxy/api/views/base_views.py", line 241, in make_response
    return self.get_paginated_response(serializer.data)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 742, in data
    ret = super(ListSerializer, self).data
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 660, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/galaxy/galaxy/api/serializers/roles.py", line 60, in to_representation
    .to_representation(instance))
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 504, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/fields.py", line 1816, in to_representation
    return method(value)
  File "/galaxy/galaxy/api/serializers/roles.py", line 92, in get_related
    'api:role_versions_list', args=(obj.pk,)),
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'role_versions_list' not found. 'role_versions_list' is not a valid view function or pattern name.
```

ansible-galaxy console output
(the JSON decode error is really a client bug, but that is after the 500 from galaxy)

```
(galaxy-py27) [newswoop:F27:galaxy-cli (split_up %)]$ GALAXY_CLI_LOG_LEVEL=DEBUG ansible-galaxy -s http://localhost:8000 search this_is_a_search_term
[16:08:59,389 08438 D] ansible_galaxy_cli.main main:21 - args: ['/home/adrian/venvs/galaxy-py27/bin/ansible-galaxy', '-s', 'http://localhost:8000', 'search', 'this_is_a_search_term']
[16:08:59,389 08438 I] ansible_galaxy_cli.cli run:160 - No config file found; using defaults
[16:08:59,514 08438 E] ansible_galaxy.flat_rest_api.api.GalaxyAPI __call_galaxy:105 - HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/home/adrian/src/galaxy-cli/ansible_galaxy/flat_rest_api/api.py", line 95, in __call_galaxy
    timeout=20)
  File "/home/adrian/src/galaxy-cli/ansible_galaxy/flat_rest_api/urls.py", line 923, in open_url
    r = urllib_request.urlopen(*urlopen_args)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/home/adrian/venvs/galaxy-py27/bin/ansible-galaxy", line 11, in <module>
    load_entry_point('ansible-galaxy-cli', 'console_scripts', 'ansible-galaxy')()
  File "/home/adrian/src/galaxy-cli/ansible_galaxy_cli/main.py", line 31, in main
    exit_code = cli.run()
  File "/home/adrian/src/galaxy-cli/ansible_galaxy_cli/cli/galaxy.py", line 165, in run
    self.execute()
  File "/home/adrian/src/galaxy-cli/ansible_galaxy_cli/cli/__init__.py", line 144, in execute
    fn()
  File "/home/adrian/src/galaxy-cli/ansible_galaxy_cli/cli/galaxy.py", line 679, in execute_search
    tags=self.options.galaxy_tags, author=self.options.author, page_size=page_size)
  File "/home/adrian/src/galaxy-cli/ansible_galaxy/flat_rest_api/api.py", line 55, in wrapped
    return method(self, *args, **kwargs)
  File "/home/adrian/src/galaxy-cli/ansible_galaxy/flat_rest_api/api.py", line 322, in search_roles
    data = self.__call_galaxy(search_url)
  File "/home/adrian/src/galaxy-cli/ansible_galaxy/flat_rest_api/api.py", line 55, in wrapped
    return method(self, *args, **kwargs)
  File "/home/adrian/src/galaxy-cli/ansible_galaxy/flat_rest_api/api.py", line 106, in __call_galaxy
    res = json.loads(to_text(e.fp.read(), errors='surrogate_or_strict'))
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

ansible-galaxy client log

```
[2018-05-11 16:02:09,241 07506 D] ansible_galaxy_cli.main main:21 - args: ['/home/adrian/venvs/galaxy-py27/bin/ansible-galaxy', 'search', 'this_is_a_search_term']
[2018-05-11 16:02:09,242 07506 I] ansible_galaxy_cli.cli run:160 - No config file found; using defaults
[2018-05-11 16:02:09,360 07506 E] ansible_galaxy.flat_rest_api.api.GalaxyAPI __call_galaxy:105 - HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/home/adrian/src/galaxy-cli/ansible_galaxy/flat_rest_api/api.py", line 95, in __call_galaxy
    timeout=20)
  File "/home/adrian/src/galaxy-cli/ansible_galaxy/flat_rest_api/urls.py", line 923, in open_url
    r = urllib_request.urlopen(*urlopen_args)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by alikins** [comment]
Looks like it happens for any search:

```
[2018-05-11 16:24:52,210 9824:Thread-4 E] django.request exception.py handle_uncaught_exception:135 : Internal Server Error: /api/v1/search/content/
```

Going 'search' from web ui hits it as well.
