### ISSUE TITLE
Import error after repository rename

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy#543]
##### SUMMARY
Getting a traceback when import a role. 

##### STEPS TO REPRODUCE
The repository `chouseknecht/adb-up-role` was previously imported under Galaxy v2. It's a pre-existing role that passed through the upgrade to v3. 

In the UI, change the name of the repository to `my-adb-role`. This initiates an import.

##### EXPECTED RESULTS
Successful role import.

##### ACTUAL RESULTS
Received the following traceback:

```
[2018-05-16 09:27:05,327: ERROR/MainProcess] Task galaxy.worker.tasks.import_repository[f840e508-0623-4c3f-9895-528ed389cfe3] raised unexpected: OSError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/galaxy/galaxy/worker/tasks.py", line 58, in import_repository
    _import_repository(import_task, logger)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/galaxy/galaxy/worker/tasks.py", line 93, in _import_repository
    logger=logger)
  File "/galaxy/galaxy/importer/repository.py", line 38, in import_repository
    return load_repository(clone_dir, logger)
  File "/galaxy/galaxy/importer/repository.py", line 48, in load_repository
    return RepositoryLoader(directory, logger=logger).load()
  File "/galaxy/galaxy/importer/repository.py", line 75, in load
    result = list(self._get_contents())
  File "/galaxy/galaxy/importer/repository.py", line 100, in _get_contents
    lint_result = loader.lint()
  File "/galaxy/galaxy/importer/loaders/base.py", line 83, in lint
    for message in linter_cls(self.root).check_files(self.rel_path):
  File "/galaxy/galaxy/importer/linters/__init__.py", line 71, in _check_files
    proc = subprocess.Popen(cmd, cwd=self.root, stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by chouseknecht** [comment]
Seeing this with a regular import too. Not limited by repository rename. 

## Steps to reproduce
- Add a new Namespace, 'atestuseraccount'
- Add provider namespace 'atestuseraccount' to the Namespace
- Add repository `ansible-testing-content`

**Comment by chouseknecht** [comment]
User error. My Galaxy container did not have all the Python dependencies installed. After running `source ${VENV_BIN}/activate; pip install -r requirements.yml` inside the container, imports started working.
