### ISSUE TITLE
Content search API returns code 500

### ISSUE THREAD

**Issue by cutwater** [ansible/galaxy#680]
##### SUMMARY

API endpoint `/api/v1/content/search` fails with error 500 on Galaxy QA.

Server log:

```
2018-06-20 06:41:55,198 ERROR exception: Internal Server Error: /api/v1/search/content/
  | Traceback (most recent call last):
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
  | response = get_response(request)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
  | response = self._get_response(request)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
  | response = self.process_exception_by_middleware(e, request)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
  | response = wrapped_callback(request, *callback_args, **callback_kwargs)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
  | return view_func(*args, **kwargs)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
  | return self.dispatch(request, *args, **kwargs)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 494, in dispatch
  | response = self.handle_exception(exc)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 454, in handle_exception
  | self.raise_uncaught_exception(exc)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/views.py", line 491, in dispatch
  | response = handler(request, *args, **kwargs)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/generics.py", line 201, in get
  | return self.list(request, *args, **kwargs)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/galaxy/api/views/search.py", line 115, in list
  | return self.make_response(queryset)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/galaxy/api/views/base_views.py", line 220, in make_response
  | page = self.paginate_queryset(queryset)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/generics.py", line 173, in paginate_queryset
  | return self.paginator.paginate_queryset(queryset, self.request, view=self)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/rest_framework/pagination.py", line 226, in paginate_queryset
  | return list(self.page)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/paginator.py", line 137, in __len__
  | return len(self.object_list)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __len__
  | self._fetch_all()
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
  | self._result_cache = list(self._iterable_class(self))
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
  | results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
  | sql, params = self.as_sql()
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 428, in as_sql
  | extra_select, order_by, group_by = self.pre_sql_setup()
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 47, in pre_sql_setup
  | order_by = self.get_order_by()
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 298, in get_order_by
  | field, self.query.get_meta(), default_order=asc))
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 606, in find_ordering_name
  | field, targets, alias, joins, path, opts = self._setup_joins(pieces, opts, alias)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 639, in _setup_joins
  | pieces, opts, alias)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1417, in setup_joins
  | names, opts, allow_many, fail_on_missing=True)
  | File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1352, in names_to_path
  | "Choices are: %s" % (name, ", ".join(available)))
  | FieldError: Cannot resolve keyword 'download_count' into field. Choices are: active, categories, cloud_platforms, company, container_yml, content_type, content_type_id, created, dependencies, description, download_count_ln, download_rank, featured, github_default_branch, id, imported, is_valid, license, metadata, min_ansible_container_version, min_ansible_version, modified, name, namespace, namespace_id, original_name, platforms, readme, readme_id, relevance, repository, repository_id, role_type, search_rank, search_vector, tags, videos
```

**Comment by cutwater** [comment]
RCA:

Bug is reproduced when requesting content search ordering by `download_count`.
This happens because `download_count` field was moved out of `Content` model and due to direct mapping between `order_by` value and model fields endpoint fails.

Solution:
As a workaround we can update UI to generate `order_by=repository__download_count` query.
