### ISSUE TITLE
New user creation fails with a 500 Error

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy#689]
I created a new user on github (https://github.com/newswangerd-test) and tried to sign up for an account on galaxy-qa, and I got this error. I think that the problem had to do with not setting up a name on my GitHub account, because adding my name in github seems to have solved the problem.

```
2018-06-20 16:13:28,468 ERROR exception: Internal Server Error: /accounts/github/login/callback/
Traceback (most recent call last):
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 143, in dispatch
    return complete_social_login(request, login)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/allauth/socialaccount/helpers.py", line 153, in complete_social_login
    return _complete_social_login(request, sociallogin)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/allauth/socialaccount/helpers.py", line 168, in _complete_social_login
    ret = _login_social_account(request, sociallogin)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/allauth/socialaccount/helpers.py", line 55, in _login_social_account
    signal_kwargs={"sociallogin": sociallogin})
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/allauth/account/utils.py", line 165, in perform_login
    **signal_kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/galaxy/main/signals/handlers.py", line 75, in user_logged_in_handler
    name=login, defaults=defaults)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/query.py", line 506, in _create_object_from_params
    six.reraise(*exc_info)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/query.py", line 498, in _create_object_from_params
    obj = self.create(**params)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: null value in column "description" violates not-null constraint
DETAIL:  Failing row contains (5674, 2018-06-20 20:13:28.461416+00, 2018-06-20 20:13:28.461441+00, null, t, newswangerd-test, https://avatars1.githubusercontent.com/u/40441481?v=4 , null, null, davidn@redhat.com, , f).

10.129.2.1 - - [20/Jun/2018:16:13:28 -0400] "GET /accounts/github/login/callback/?code=eb78e1d99fd5f21b33c1&state=eZReDfbVUgQ8 HTTP/1.1" 500 27 "https://galaxy-qa.ansible.com/login " "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
```

**Comment by chouseknecht** [comment]
@newswangerd 

This is a bug in the login signal handler. We default the Namespace description attribute to the GitHub name value 65. If the GitHub name is empty, that would cause the 500. 

Since you're going to be refactoring this code, please fix this as well. If name is not set in GitHub, let's default it to the login value.
