### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: [Errno 21] Is a directory

### ISSUE THREAD

**Issue by mattthehearn** [ansible/galaxy#704]
##### SUMMARY
Getting a funny error when attempting to install roles.  First noticed within a molecule test, but fails even when the galaxy command is run manually.

##### STEPS TO REPRODUCE
/usr/bin/ansible-galaxy install --role-file=meta/requirements.yml --roles-path=/tmp/molecule/ansible-role_sssd/docker/roles --force -vvv

##### EXPECTED RESULTS
Successfully install the roles inside the requirements.yml file, placed in the roles-path.

##### ACTUAL RESULTS
```
15:57 $ /usr/bin/ansible-galaxy install --role-file=meta/requirements.yml --roles-path=/tmp/molecule/ansible-role_sssd/docker/roles --force -vvv
ansible-galaxy 2.5.2
  config file = None
  configured module search path = [u'/home/ermhearn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
No config file found; using defaults
Opened /home/ermhearn/.ansible_galaxy
found role {'scm': 'git', 'src': 'https://cscgithub.cscglobal.com/INFRA/ansible-role_facts.git', 'version': '', 'name': 'ansible-role_facts'} in yaml file
found role {'scm': 'git', 'src': 'https://cscgithub.cscglobal.com/INFRA/ansible-role_satellite.git', 'version': '', 'name': 'ansible-role_satellite'} in yaml file
Processing role ansible-role_facts
- extracting ansible-role_facts to /tmp/molecule/ansible-role_sssd/docker/roles/ansible-role_facts
ERROR! Unexpected Exception, this is probably a bug: [Errno 21] Is a directory: u'/tmp/molecule/ansible-role_sssd/docker/roles/ansible-role_facts'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 150, in run
    self.execute()
  File "/usr/lib/python2.7/site-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/usr/lib/python2.7/site-packages/ansible/cli/galaxy.py", line 393, in execute_install
    installed = role.install()
  File "/usr/lib/python2.7/site-packages/ansible/galaxy/role.py", line 323, in install
    role_tar_file.extract(member, self.path)
  File "/usr/lib64/python2.7/tarfile.py", line 2084, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib64/python2.7/tarfile.py", line 2160, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib64/python2.7/tarfile.py", line 2200, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 21] Is a directory: u'/tmp/molecule/ansible-role_sssd/docker/roles/ansible-role_facts'
```

**Comment by mattthehearn** [comment]
Figured it out!  There was a weird "Jenkinsfile~" file in the role I was trying to install with galaxy, probably a saved backup file from VSCode that made it into my git repo.  Once I got rid of that, galaxy install worked fine.
