### ISSUE TITLE
104 Connection reset by peer while downloading role geerlingguy.php

### ISSUE THREAD

**Issue by webarchitect609** [ansible/galaxy#807]
##### SUMMARY
Had a problem: impossible to download geerlingguy.php ansible role!

Tried to provision vagrant with ansible. I have a bunch of roles: 

- src: geerlingguy.mysql
- src: geerlingguy.php
- src: geerlingguy.nginx
- src: geerlingguy.git
- src: geerlingguy.composer
- src: geerlingguy.rabbitmq

But **only** when process tries to download geerlingguy.php it fails with message: 

> - downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.6.0.tar.gz
>  [ERROR]: failed to download the file: (104, 'Connection reset by peer')

##### STEPS TO REPRODUCE
Just execute single command and you will get it: 
`ansible-galaxy install geerlingguy.php`

Installed software versions:
Ubuntu 14.04 LTS
Python = 2.7.6
ansible-galaxy = 2.5.4
urllib3 = 1.7.1
pyOpenSSL = 0.13
ndg-httpsclient = 0.5.0
pyasn1 = 0.4.3

##### EXPECTED RESULTS
Successful installation of mentioned role geerlingguy.php as it was hundreds times before. 

##### ACTUAL RESULTS
Screenshot: http://joxi.ru/DmBDEZIJdyQ9AP?d=1 
Text version:
```
$ ansible-galaxy install geerlingguy.php
- downloading role 'php', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.6.0.tar.gz
 [ERROR]: failed to download the file: (104, 'Connection reset by peer')

 [WARNING]: - geerlingguy.php was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by chouseknecht** [comment]
Could this be a timing thing? We were doing an upgrade this morning, so perhaps your connection got reset during the deployment. 

I can install it successfully, FWIW:

```
ansible-galaxy install geerlingguy.php
- downloading role 'php', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.6.0.tar.gz
- extracting geerlingguy.php to /Users/chouseknecht/.ansible/roles/geerlingguy.php
- geerlingguy.php (3.6.0) was installed successfully
```

**Comment by webarchitect609** [comment]
Maybe, this is something about network? Currently I'm in Moscow. For more than an hour I'm trying to install all the roles I mentioned above. Everything is OK but `geerlingguy.php` . Should I try it later again? After, let's say, 3-4 hours?

**Comment by robertdebock** [comment]
Works for me too, you may try to simply paste the URL in the browser:
https://github.com/geerlingguy/ansible-role-php/archive/3.6.0.tar.gz

**Comment by webarchitect609** [comment]
> Works for me too, you may try to simply paste the URL in the browser:
> https://github.com/geerlingguy/ansible-role-php/archive/3.6.0.tar.gz

It works normally but problem still exists. And just a second ago I've got this kind of error, but I can't reproduce it anymore: 
```
$ ansible-galaxy install geerlingguy.php
- downloading role 'php', owned by geerlingguy
ERROR! Unexpected Exception, this is probably a bug: object of type 'NoneType' has no len()
to see the full traceback, use -vvv
```

So here is more detailed information using `-vvv` option: 
```
$ ansible-galaxy install geerlingguy.php -vvv
ansible-galaxy 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gripinskiy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
Using /etc/ansible/ansible.cfg as config file
Opened /home/gripinskiy/.ansible_galaxy
Processing role geerlingguy.php 
Opened /home/gripinskiy/.ansible_galaxy
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=php
https://galaxy.ansible.com/api/v1/roles/432/versions/?page_size=50
https://galaxy.ansible.com/api/v1/roles/432/versions/?page=2&page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.6.0.tar.gz
 [ERROR]: failed to download the file: (104, 'Connection reset by peer')

 [WARNING]: - geerlingguy.php was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

Maybe this is because I have python version = 2.7.6 + urllib3, pyopenssl, ndg-httpsclient, pyasn1 installed for SNI verification? Things are very uncanny now. :(

**Comment by webarchitect609** [comment]
I have added more details about OS and packages versions to bug description. At another machine with python version = 2.7.14 bug is not reproduced, but on mine I can't install this version of Python as it raises a lot of conflicts.

**Comment by webarchitect609** [comment]
New clues, guys! So, today situation looks like this: two serial tries of installing.

```
$ ansible-galaxy install geerlingguy.php
- downloading role 'php', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.6.0.tar.gz
 [ERROR]: failed to download the file: (104, 'Connection reset by peer')

 [WARNING]: - geerlingguy.php was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.


$ ansible-galaxy install geerlingguy.php
- downloading role 'php', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.6.0.tar.gz
- extracting geerlingguy.php to /home/gripinskiy/.ansible/roles/geerlingguy.php
- geerlingguy.php (3.6.0) was installed successfully
```
Second one is successfull! Why? Maybe, because some web-server configured in the way to prohibit making requests ending with '*.php'. Look closer: here it is! 

"geerlingguy.php" seems to be an *.php file! That what needs to be checked to avoid this bug.

**Comment by cutwater** [comment]
@webarchitect609 Thanks for reporting details. It's unlikely to be web server configuration issue (in context of handling *.php urls), because second installation went successfully.
Since we didn't have any deployments today the issue doesn't seem to be related with galaxy.

Moreover according to short ansible-galaxy tool log, issue happend when galaxy tried to download archive from github. So it's possible that the issue is not related to galaxy servers at all.

I assume github may rate limit archive downloads, but it requires additional investigation.

**Comment by Wilkun** [comment]
I have similiar issue just with this package. I'm running ansible_local provision on vagrant, with an ubuntu/trusty64 box.

My `requirements.yml`:
```yml
---
- src: geerlingguy.firewall
- src: geerlingguy.ntp
- src: geerlingguy.git
- src: geerlingguy.repo-epel
- src: geerlingguy.repo-remi
- src: geerlingguy.mysql
- src: geerlingguy.apache
- src: geerlingguy.composer
- src: geerlingguy.php-mysql
- src: geerlingguy.php-versions
- src: geerlingguy.phpmyadmin
- src: geerlingguy.php
  version: 3.6.0
```

When I'm running the code from inside the box, using `vagrant ssh`:
```sh
vagrant@lamp:~$ sudo ansible-galaxy install geerlingguy.php -p /etc/ansible/roles -vvv
ansible-galaxy 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
Using /etc/ansible/ansible.cfg as config file
Opened /home/vagrant/.ansible_galaxy
Processing role geerlingguy.php
Opened /home/vagrant/.ansible_galaxy
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=php
https://galaxy.ansible.com/api/v1/roles/432/versions/?page_size=50
https://galaxy.ansible.com/api/v1/roles/432/versions/?page=2&page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.6.1.tar.gz
 [ERROR]: failed to download the file: (104, 'Connection reset by peer')

 [WARNING]: - geerlingguy.php was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

When I run the `requirements.yml`:
```sh
vagrant@lamp:/vagrant$ sudo ansible-galaxy install -r requirements.yml -p /etc/ansible/roles -f -vvv
ansible-galaxy 2.6.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
Using /etc/ansible/ansible.cfg as config file
Opened /home/vagrant/.ansible_galaxy
found role {'scm': None, 'src': 'geerlingguy.firewall', 'version': '', 'name': 'geerlingguy.firewall'} in yaml file
found role {'scm': None, 'src': 'geerlingguy.ntp', 'version': '', 'name': 'geerlingguy.ntp'} in yaml file
found role {'scm': None, 'src': 'geerlingguy.git', 'version': '', 'name': 'geerlingguy.git'} in yaml file
found role {'scm': None, 'src': 'geerlingguy.repo-epel', 'version': '', 'name': 'geerlingguy.repo-epel'} in yaml file
found role {'scm': None, 'src': 'geerlingguy.repo-remi', 'version': '', 'name': 'geerlingguy.repo-remi'} in yaml file
found role {'scm': None, 'src': 'geerlingguy.mysql', 'version': '', 'name': 'geerlingguy.mysql'} in yaml file
found role {'scm': None, 'src': 'geerlingguy.apache', 'version': '', 'name': 'geerlingguy.apache'} in yaml file
found role {'scm': None, 'src': 'geerlingguy.composer', 'version': '', 'name': 'geerlingguy.composer'} in yaml file
found role {'scm': None, 'src': 'geerlingguy.php-mysql', 'version': '', 'name': 'geerlingguy.php-mysql'} in yaml file
found role {'scm': None, 'src': 'geerlingguy.php-versions', 'version': '', 'name': 'geerlingguy.php-versions'} in yaml file
found role {'scm': None, 'src': 'geerlingguy.phpmyadmin', 'version': '', 'name': 'geerlingguy.phpmyadmin'} in yaml file
found role {'scm': None, 'src': 'geerlingguy.php', 'version': '3.6.0', 'name': 'geerlingguy.php'} in yaml file
Processing role geerlingguy.firewall
- changing role geerlingguy.firewall from 2.4.0 to unspecified
Opened /home/vagrant/.ansible_galaxy
- downloading role 'firewall', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=firewall
https://galaxy.ansible.com/api/v1/roles/451/versions/?page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-firewall/archive/2.4.0.tar.gz
- extracting geerlingguy.firewall to /etc/ansible/roles/geerlingguy.firewall
- geerlingguy.firewall (2.4.0) was installed successfully
Processing role geerlingguy.ntp
- changing role geerlingguy.ntp from 1.6.2 to unspecified
Opened /home/vagrant/.ansible_galaxy
- downloading role 'ntp', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=ntp
https://galaxy.ansible.com/api/v1/roles/464/versions/?page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-ntp/archive/1.6.2.tar.gz
- extracting geerlingguy.ntp to /etc/ansible/roles/geerlingguy.ntp
- geerlingguy.ntp (1.6.2) was installed successfully
Processing role geerlingguy.git
- changing role geerlingguy.git from 2.0.2 to unspecified
Opened /home/vagrant/.ansible_galaxy
- downloading role 'git', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=git
https://galaxy.ansible.com/api/v1/roles/431/versions/?page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-git/archive/2.0.2.tar.gz
- extracting geerlingguy.git to /etc/ansible/roles/geerlingguy.git
- geerlingguy.git (2.0.2) was installed successfully
Processing role geerlingguy.repo-epel
- changing role geerlingguy.repo-epel from 1.2.3 to unspecified
Opened /home/vagrant/.ansible_galaxy
- downloading role 'repo-epel', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=repo-epel
https://galaxy.ansible.com/api/v1/roles/436/versions/?page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-repo-epel/archive/1.2.3.tar.gz
- extracting geerlingguy.repo-epel to /etc/ansible/roles/geerlingguy.repo-epel
- geerlingguy.repo-epel (1.2.3) was installed successfully
Processing role geerlingguy.repo-remi
- changing role geerlingguy.repo-remi from 1.2.0 to unspecified
Opened /home/vagrant/.ansible_galaxy
- downloading role 'repo-remi', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=repo-remi
https://galaxy.ansible.com/api/v1/roles/437/versions/?page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-repo-remi/archive/1.2.0.tar.gz
- extracting geerlingguy.repo-remi to /etc/ansible/roles/geerlingguy.repo-remi
- geerlingguy.repo-remi (1.2.0) was installed successfully
Processing role geerlingguy.mysql
- changing role geerlingguy.mysql from 2.9.3 to unspecified
Opened /home/vagrant/.ansible_galaxy
- downloading role 'mysql', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=mysql
https://galaxy.ansible.com/api/v1/roles/435/versions/?page_size=50
https://galaxy.ansible.com/api/v1/roles/435/versions/?page=2&page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-mysql/archive/2.9.3.tar.gz
- extracting geerlingguy.mysql to /etc/ansible/roles/geerlingguy.mysql
- geerlingguy.mysql (2.9.3) was installed successfully
Processing role geerlingguy.apache
- changing role geerlingguy.apache from 3.0.0 to unspecified
Opened /home/vagrant/.ansible_galaxy
- downloading role 'apache', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=apache
https://galaxy.ansible.com/api/v1/roles/428/versions/?page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-apache/archive/3.0.0.tar.gz
- extracting geerlingguy.apache to /etc/ansible/roles/geerlingguy.apache
- geerlingguy.apache (3.0.0) was installed successfully
Processing role geerlingguy.composer
- changing role geerlingguy.composer from 1.7.2 to unspecified
Opened /home/vagrant/.ansible_galaxy
- downloading role 'composer', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=composer
https://galaxy.ansible.com/api/v1/roles/429/versions/?page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-composer/archive/1.7.2.tar.gz
- extracting geerlingguy.composer to /etc/ansible/roles/geerlingguy.composer
- geerlingguy.composer (1.7.2) was installed successfully
Processing role geerlingguy.php-mysql
- changing role geerlingguy.php-mysql from 2.0.1 to unspecified
Opened /home/vagrant/.ansible_galaxy
- downloading role 'php-mysql', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=php-mysql
https://galaxy.ansible.com/api/v1/roles/434/versions/?page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-php-mysql/archive/2.0.1.tar.gz
- extracting geerlingguy.php-mysql to /etc/ansible/roles/geerlingguy.php-mysql
- geerlingguy.php-mysql (2.0.1) was installed successfully
- dependency geerlingguy.php already pending installation.
Processing role geerlingguy.php-versions
- changing role geerlingguy.php-versions from 2.1.3 to unspecified
Opened /home/vagrant/.ansible_galaxy
- downloading role 'php-versions', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=php-versions
https://galaxy.ansible.com/api/v1/roles/27117/versions/?page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-php-versions/archive/2.1.3.tar.gz
- extracting geerlingguy.php-versions to /etc/ansible/roles/geerlingguy.php-versions
- geerlingguy.php-versions (2.1.3) was installed successfully
Processing role geerlingguy.phpmyadmin
- changing role geerlingguy.phpmyadmin from 1.3.2 to unspecified
Opened /home/vagrant/.ansible_galaxy
- downloading role 'phpmyadmin', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=phpmyadmin
https://galaxy.ansible.com/api/v1/roles/462/versions/?page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-phpmyadmin/archive/1.3.2.tar.gz
- extracting geerlingguy.phpmyadmin to /etc/ansible/roles/geerlingguy.phpmyadmin
- geerlingguy.phpmyadmin (1.3.2) was installed successfully
 [WARNING]: - dependency geerlingguy.apache from role geerlingguy.phpmyadmin differs from already installed version (3.0.0), skipping

 [WARNING]: - dependency geerlingguy.mysql from role geerlingguy.phpmyadmin differs from already installed version (2.9.3), skipping

 [WARNING]: - dependency geerlingguy.php-mysql from role geerlingguy.phpmyadmin differs from already installed version (2.0.1), skipping

- dependency geerlingguy.php already pending installation.
Processing role geerlingguy.php
Opened /home/vagrant/.ansible_galaxy
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=php
https://galaxy.ansible.com/api/v1/roles/432/versions/?page_size=50
https://galaxy.ansible.com/api/v1/roles/432/versions/?page=2&page_size=50
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/3.6.0.tar.gz
 [ERROR]: failed to download the file: (104, 'Connection reset by peer')

 [WARNING]: - geerlingguy.php was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

I can move the geerlingguy.php in requirements to be loaded in different order, but the effect is the same.

**Comment by webarchitect609** [comment]
@cutwater , as it does not seems this problem is going to vanish and more people have encountered it, I have written to github's support team about this and hope they will fix it or give us a hint how it can be worked around.

**Comment by gdmello** [comment]
Have the same issue on a different role, had to d/l via curl and move the untar'ed directory to `~/.ansible/roles`.

**Comment by kentr** [comment]
In case it's related:

I'm getting the `ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object is not iterable` error.

It's very repeatable.  The only time I have _not_ gotten the error is when I remove all other roles from the role-file.

**Debug output:**

```
Processing role geerlingguy.php 
- changing role geerlingguy.php from 3.7.0 to 3.7.0
Opened /Users/Work/.ansible_galaxy
Initial connection to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/api/v1/roles/?owner__username=geerlingguy&name=php
https://galaxy.ansible.com/api/v1/roles/432/versions/?page_size=50
ERROR! Unexpected Exception, this is probably a bug: 'NoneType' object is not iterable
the full traceback was:

Traceback (most recent call last):
  File "/Users/Work/Library/Python/2.7/bin/ansible-galaxy", line 118, in <module>
    exit_code = cli.run()
  File "/Users/Work/Library/Python/2.7/lib/python/site-packages/ansible/cli/galaxy.py", line 162, in run
    self.execute()
  File "/Users/Work/Library/Python/2.7/lib/python/site-packages/ansible/cli/__init__.py", line 155, in execute
    fn()
  File "/Users/Work/Library/Python/2.7/lib/python/site-packages/ansible/cli/galaxy.py", line 398, in execute_install
    installed = role.install()
  File "/Users/Work/Library/Python/2.7/lib/python/site-packages/ansible/galaxy/role.py", line 247, in install
    for role_version in role_versions:
TypeError: 'NoneType' object is not iterable
```

**Comment by kentr** [comment]
Looks like the `NoneType` error is [already reported in the Ansible repo](https://github.com/ansible/ansible/issues/46650).
