### ISSUE TITLE
Roles that are already imported but 'invalid' can not be displayed properly

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#810]
##### SUMMARY

While some roles are displayed fine, there are some roles that hangs forever during load

##### STEPS TO REPRODUCE

goto https://galaxy.ansible.com/davidwittman/redis
everything is ok
<img width="713" alt="image" src="https://user-images.githubusercontent.com/1472728/42217276-30c53c7e-7ecd-11e8-9231-4065a85a226a.png">

goto https://galaxy.ansible.com/lateralthoughts/ansible-play2
<img width="859" alt="image" src="https://user-images.githubusercontent.com/1472728/42217254-1f5f11ee-7ecd-11e8-9002-aa56b9494c11.png">

the page is loading forever

##### ACTUAL RESULTS

```

```

**Comment by chouseknecht** [comment]
The page for https://galaxy.ansible.com/lateralthoughts/ansible-play2 loads fine for me. Not able to reproduce.

**Comment by akaRem** [comment]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/1472728/42217887-8dd83e64-7ecf-11e8-9300-441f5c0a3a85.png">

**Comment by akaRem** [comment]
@chouseknecht probably you have some other permissions than non-auth user
I see this resp
```
HTTP 403 Forbidden
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "You do not have permission to perform this action."
}
```

This is fine. But you could display that message instead of showing forever-load spinner

**Comment by chouseknecht** [comment]
The ContentDetail view returns a 403 when Content.is_valid = False. Not sure how we're handling failed imports, and what state both Content and Repository are in after failure. Let's review.

**Comment by akaRem** [comment]
@chouseknecht I think the main issue here is that all occur. of `summary_fields` in this repo are typed as `any` ( = untyped ). So TS can't help you to find such bugs.

**Comment by akaRem** [comment]
BTW it looks like you fixed _something_ and this error does not appear any more.
You could mark issue as resolved, but I suppose that root case is not fixed yet.

**Comment by chouseknecht** [comment]
@cutwater in the Content and ContentSearch Serializers, please make sure we surface `is_valid` and `active` values.

We should probably remove from the returned results anything where `is_valid` = False

**Comment by alikins** [comment]
The meta/main.yml in that repo appears to be invalid yaml. 
https://github.com/LateralThoughts/ansible-play2/pull/1 has a fix for the yaml.

With the fix I was able to import it into https://galaxy.ansible.com/alikins/ansible_play2



Without the above fix:
Trying to import a fork of this into devel (49dc6bae113370bb736adca7b107017b74a05596) fails to import.
The error shown in the web ui is:

```
Starting import: task_id=10, repository=alikins/ansible-play2

Task "10" failed: while parsing a block mapping in "/tmp/tmp9a0IAy/meta/main.yml", line 3, column 3 expected <block end>, but found '-' in "/tmp/tmp9a0IAy/meta/main.yml", line 8, column 3
```

With celery logging cranked up, server logs are:

```
[2018-11-15 13:22:29,617 none 7452:MainThread ERROR] galaxy.worker.tasks tasks.py import_repository:152 : while parsing a block mapping
  in "/tmp/tmp9a0IAy/meta/main.yml", line 3, column 3
expected <block end>, but found '-'
  in "/tmp/tmp9a0IAy/meta/main.yml", line 8, column 3
Traceback (most recent call last):
  File "/galaxy/galaxy/worker/tasks.py", line 136, in import_repository
    _import_repository(import_task, logger)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/galaxy/galaxy/worker/tasks.py", line 176, in _import_repository
    logger=logger)
  File "/galaxy/galaxy/importer/repository.py", line 40, in import_repository
    return load_repository(clone_dir, logger)
  File "/galaxy/galaxy/importer/repository.py", line 50, in load_repository
    return RepositoryLoader(directory, logger=logger).load()
  File "/galaxy/galaxy/importer/repository.py", line 78, in load
    result = list(self._load_contents(contents))
  File "/galaxy/galaxy/importer/repository.py", line 115, in _load_contents
    content = loader.load()
  File "/galaxy/galaxy/importer/loaders/role.py", line 276, in load
    meta_parser = self._get_meta_parser()
  File "/galaxy/galaxy/importer/loaders/role.py", line 325, in _get_meta_parser
    meta = self._load_metadata()
  File "/galaxy/galaxy/importer/loaders/role.py", line 364, in _load_metadata
    metadata = yaml.safe_load(fp)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/var/lib/galaxy/venv/lib/python2.7/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "/tmp/tmp9a0IAy/meta/main.yml", line 3, column 3
expected <block end>, but found '-'
  in "/tmp/tmp9a0IAy/meta/main.yml", line 8, column 3
```

With the fix above:

```
INFO Starting import: task_id=319477, repository=alikins/ansible-play2
INFO Content search - Looking for file "apb.yml"
INFO Content search - Looking for top level role metadata file
WARNING [role] Missing 'dependencies' field in metadata.
WARNING [role] Found "categories" in metadata. Update the metadata to use "galaxy_tags" rather than categories.
INFO [role] Linting...
ERROR [role] ./vars/main.yml:3:12: [error] too many spaces before colon (colons)
ERROR Lint failed
INFO [role] Created new Content instance: id=32725, content_type="role", name="ansible_play2"
INFO [role] Adding role metadata tags
INFO [role] Adding role platforms
INFO Updating repository versions...
Import completed
```

**Comment by alikins** [comment]
I'm guessing the version of that role at https://galaxy.ansible.com/lateralthoughts/ansible-play2  also failed to import properly, but probably failed in a more lenient way in an older version of the code, leaving an otherwise empty galaxy page for it,
