### ISSUE TITLE
JS testing not working

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#873]
##### SUMMARY

I didn't find any targets for JS testing.

After adding 
```
diff --git a/Makefile b/Makefile
index 7436fee..a39e858 100644
--- a/Makefile
+++ b/Makefile
@@ -144,6 +144,11 @@ dev/jslint:
        @echo "Linting Javascript..."
        @$(DOCKER_COMPOSE) exec galaxy bash -c 'cd galaxyui; ng lint'

+.PHONY: dev/jstest
+dev/jstest:
+       @echo "Testing Javascript..."
+       @$(DOCKER_COMPOSE) exec galaxy bash -c 'cd galaxyui; ng test'
+
 .PHONY: dev/test
 dev/test:
        @echo "Running tests"
```

I got following error:

```
➜  galaxy git:(devel) ✗ make dev/jstest
Testing Javascript...
Your global Angular CLI version (6.0.8) is greater than your local
version (6.0.5). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
ENOENT: no such file or directory, stat '/galaxy/galaxyui/src/favicon.ico'
Error: ENOENT: no such file or directory, stat '/galaxy/galaxyui/src/favicon.ico'
    at Object.fs.statSync (fs.js:948:11)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/galaxy/galaxyui/node_modules/@angular-devkit/core/node/host.js:212:25)
    at Observable.subscribe (/galaxy/galaxyui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:162:69)
    at MapOperator.call (/galaxy/galaxyui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/map.js:62:23)
    at Observable.subscribe (/galaxy/galaxyui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:159:22)
    at CatchOperator.call (/galaxy/galaxyui/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/catchError.js:28:23)
    at Observable.subscribe (/galaxy/galaxyui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:159:22)
    at MapOperator.call (/galaxy/galaxyui/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/map.js:62:23)
    at Observable.subscribe (/galaxy/galaxyui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:159:22)
    at /galaxy/galaxyui/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeToObservable.js:16:20
    at Object.subscribeToResult (/galaxy/galaxyui/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at new ForkJoinSubscriber (/galaxy/galaxyui/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/observable/forkJoin.js:165:57)
    at Observable._subscribe (/galaxy/galaxyui/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/observable/forkJoin.js:145:16)
    at Observable.subscribe (/galaxy/galaxyui/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Observable.js:162:69)
    at /galaxy/galaxyui/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/galaxy/galaxyui/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
make: *** [dev/jstest] Error 1
```
Ok, I can fix it
```
➜  galaxy git:(devel) ✗ cd ./galaxyui/src
➜  src git:(devel) ✗ ln -s ./assets/favicon.ico favicon.ico
```
Then
```
➜  galaxy git:(devel) ✗ make dev/jstest
Testing Javascript...
Your global Angular CLI version (6.0.8) is greater than your local
version (6.0.5). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
 10% building modules 1/1 modules 0 active(node:178) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
12 07 2018 19:49:42.377:WARN [karma]: No captured browser, open http://localhost:9876/
12 07 2018 19:49:42.388:INFO [karma]: Front-end scripts not present. Compiling...
✖ ｢wdm｣: Hash: 8cce8bdecb5244ae880c
Version: webpack 4.8.3
Time: 11319ms
Built at: 2018-07-12 19:49:42
       Asset      Size     Chunks  Chunk Names
     main.js  6.21 KiB       main  main
polyfills.js  6.52 KiB  polyfills  polyfills
Entrypoint main = main.js
Entrypoint polyfills = polyfills.js
[./src/polyfills.ts] 0 bytes {polyfills} [built]
[0] multi ./src/polyfills.ts 28 bytes {polyfills} [built]
[./src/test.ts] 0 bytes {main} [built]

ERROR in src/app/login/login.component.spec.ts(3,31): error TS2307: Cannot find module './home.component'.
src/app/my-content/namespace-detail/namespace-detail.resolver.service.spec.ts(3,41): error TS2307: Cannot find module './namespace-detail-resolver.service'.
src/app/my-content/namespace-list/content/repositories-content/alternate-name-modal/alternate-name-modal.component.spec.ts(3,10): error TS2305: Module '"/galaxy/galaxyui/src/app/my-content/namespace-list/content/repositories-content/alternate-name-modal/alternate-name-modal.component"' has no exported member 'AddRepositoryModalComponent'.
src/app/my-content/namespace-list/content/repositories-content/alternate-name-modal/alternate-name-modal.component.spec.ts(6,18): error TS2304: Cannot find name 'AlternateNameModalComponent'.
src/app/my-content/namespace-list/content/repositories-content/alternate-name-modal/alternate-name-modal.component.spec.ts(7,33): error TS2304: Cannot find name 'AlternateNameModalComponent'.
src/app/my-content/namespace-list/content/repositories-content/alternate-name-modal/alternate-name-modal.component.spec.ts(11,23): error TS2304: Cannot find name 'AlternateNameModalComponent'.
src/app/my-content/namespace-list/content/repositories-content/alternate-name-modal/alternate-name-modal.component.spec.ts(17,39): error TS2304: Cannot find name 'AlternateNameModalComponent'.
src/app/resources/content-blocks/content-blocks.service.spec.ts(3,29): error TS2307: Cannot find module './user.service'.
src/app/resources/content-types/content-type.service.spec.ts(3,33): error TS2307: Cannot find module './platform.service'.
src/app/resources/content/content.service.spec.ts(12,35): error TS2304: Cannot find name 'ContenthService'.
src/app/search/popular/popular.component.spec.ts(3,33): error TS2307: Cannot find module './search.component'.

12 07 2018 19:49:49.612:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
12 07 2018 19:49:49.612:INFO [launcher]: Launching browser Chrome with unlimited concurrency
12 07 2018 19:49:49.630:INFO [launcher]: Starting browser Chrome
12 07 2018 19:49:49.632:ERROR [launcher]: No binary for Chrome browser on your platform.
  Please, set "CHROME_BIN" env variable.
```
And it hangs...

Ok,
```
➜  galaxy git:(devel) ✗ cd galaxyui
➜  galaxyui git:(devel) ✗ npm run test

> galaxyui@0.0.0 test /Users/********/********/********/galaxy/galaxyui
> ng test

 10% building modules 1/1 modules 0 active(node:58818) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
12 07 2018 22:52:39.092:WARN [karma]: No captured browser, open http://localhost:9876/
12 07 2018 22:52:39.112:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
12 07 2018 22:52:39.112:INFO [launcher]: Launching browser Chrome with unlimited concurrency
12 07 2018 22:52:39.117:INFO [launcher]: Starting browser Chrome
✖ ｢wdm｣: Hash: e69fe1ce3ed480b9ec4b
Version: webpack 4.8.3
Time: 4985ms
Built at: 12.07.2018 22:52:39
       Asset      Size     Chunks  Chunk Names
     main.js  6.21 KiB       main  main
polyfills.js  6.55 KiB  polyfills  polyfills
Entrypoint main = main.js
Entrypoint polyfills = polyfills.js
[./src/polyfills.ts] 0 bytes {polyfills} [built]
[0] multi ./src/polyfills.ts 28 bytes {polyfills} [built]
[./src/test.ts] 0 bytes {main} [built]

ERROR in src/app/login/login.component.spec.ts(3,31): error TS2307: Cannot find module './home.component'.
src/app/my-content/namespace-detail/namespace-detail.resolver.service.spec.ts(3,41): error TS2307: Cannot find module './namespace-detail-resolver.service'.
src/app/my-content/namespace-list/content/repositories-content/alternate-name-modal/alternate-name-modal.component.spec.ts(3,10): error TS2305: Module '"/Users/********/********/********/galaxy/galaxyui/src/app/my-content/namespace-list/content/repositories-content/alternate-name-modal/alternate-name-modal.component"' has no exported member 'AddRepositoryModalComponent'.
src/app/my-content/namespace-list/content/repositories-content/alternate-name-modal/alternate-name-modal.component.spec.ts(6,18): error TS2304: Cannot find name 'AlternateNameModalComponent'.
src/app/my-content/namespace-list/content/repositories-content/alternate-name-modal/alternate-name-modal.component.spec.ts(7,33): error TS2304: Cannot find name 'AlternateNameModalComponent'.
src/app/my-content/namespace-list/content/repositories-content/alternate-name-modal/alternate-name-modal.component.spec.ts(11,23): error TS2304: Cannot find name 'AlternateNameModalComponent'.
src/app/my-content/namespace-list/content/repositories-content/alternate-name-modal/alternate-name-modal.component.spec.ts(17,39): error TS2304: Cannot find name 'AlternateNameModalComponent'.
src/app/resources/content-blocks/content-blocks.service.spec.ts(3,29): error TS2307: Cannot find module './user.service'.
src/app/resources/content-types/content-type.service.spec.ts(3,33): error TS2307: Cannot find module './platform.service'.
src/app/resources/content/content.service.spec.ts(12,35): error TS2304: Cannot find name 'ContenthService'.
src/app/search/popular/popular.component.spec.ts(3,33): error TS2307: Cannot find module './search.component'.

12 07 2018 22:53:39.152:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
12 07 2018 22:53:39.352:INFO [launcher]: Trying to start Chrome again (1/2).
12 07 2018 22:54:39.355:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
12 07 2018 22:54:39.565:INFO [launcher]: Trying to start Chrome again (2/2).
12 07 2018 22:55:39.583:WARN [launcher]: Chrome have not captured in 60000 ms, killing.
12 07 2018 22:55:39.722:ERROR [launcher]: Chrome failed 2 times (timeout). Giving up.
```
That's it.

How can I test JS code?

**Comment by chouseknecht** [comment]
There is no testing in place yet for JS. Something we need to get to, but haven't had the resources.

**Comment by akaRem** [comment]
@newswangerd Did you close this issue because there are no plans and needs to make them working?

**Comment by newswangerd** [comment]
@akaRem We are going to be working on testing at some point in the future, but we don't have any specific plans for it yet, so it's hard to say when this will be addressed. We'll create a new issue for this once it gets on our road map.
